export const ABOUT_ACTION_TYPE = {
  ABOUT_DATA_UPLOAD_PENDING:
    'ABOUT_ACTION_TYPE.ABOUT_DATA_UPLOAD_PENDING',
  ABOUT_DATA_UPLOAD_SUCCESS:
    'ABOUT_ACTION_TYPE.ABOUT_DATA_UPLOAD_SUCCESS',
  ABOUT_DATA_UPLOAD_ERROR:
    'ABOUT_ACTION_TYPE.ABOUT_DATA_UPLOAD_ERROR',
};
