export const SETTINGS_USER_INFO_FIELD_NAME = {
  FULLNAME: 'fullName',
  PHONE: 'phone',
};
export const SETTINGS_USER_INFO_ACTION_TYPE = {
  LOAD_PENDING: 'SETTINGS_USER_INFO_ACTION_TYPE.LOAD_PENDING',
  LOAD_SUCCESS: 'SETTINGS_USER_INFO_ACTION_TYPE.LOAD_SUCCESS',
  LOAD_ERROR: 'SETTINGS_USER_INFO_ACTION_TYPE.LOAD_ERROR',

  SAVE_PENDING: 'SETTINGS_USER_INFO_ACTION_TYPE.SAVE_PENDING',
  SAVE_SUCCESS: 'SETTINGS_USER_INFO_ACTION_TYPE.SAVE_SUCCESS',
  SAVE_ERROR: 'SETTINGS_USER_INFO_ACTION_TYPE.SAVE_ERROR',
};
