export const FAQ_PAGE_ACTION_TYPE = {
  FAQ_PAGE_UPLOAD_PENDING: 'FAQ_PAGE_ACTION_TYPE.FAQ_PAGE_UPLOAD_PENDING',
  FAQ_PAGE_UPLOAD_SUCCESS: 'FAQ_PAGE_ACTION_TYPE.FAQ_PAGE_UPLOAD_SUCCESS',
  FAQ_PAGE_UPLOAD_ERROR: 'FAQ_PAGE_ACTION_TYPE.FAQ_PAGE_UPLOAD_ERROR',
};
