export const LIKE_ACTION_TYPE = {
  LIKE_UPLOAD_PENDING: 'LIKE_ACTION_TYPE.LIKE_UPLOAD_PENDING',
  LIKE_UPLOAD_SUCCESS: 'LIKE_ACTION_TYPE.LIKE_UPLOAD_SUCCESS',
  LIKE_UPLOAD_ERROR: 'LIKE_ACTION_TYPE.LIKE_UPLOAD_ERROR',
};
