export const CREATE_MASTER_CLASS_ACTION_TYPE = {
  CREATE_MASTER_CLASS_UPLOAD_PENDING:
    'CREATE_MASTER_CLASS_ACTION_TYPE.CREATE_PRODUCT_UPLOAD_PENDING',
  CREATE_MASTER_CLASS_UPLOAD_SUCCESS:
    'CREATE_MASTER_CLASS_ACTION_TYPE.CREATE_PRODUCT_UPLOAD_SUCCESS',
  CREATE_MASTER_CLASS_UPLOAD_ERROR:
    'CREATE_MASTER_CLASS_ACTION_TYPE.CREATE_PRODUCT_UPLOAD_ERROR',
};

export const CREATE_MASTER_CLASS_FIELD_NAME = {
  NAME: 'titleRu',
  DESCRIPTION: 'descriptionRu',
  TYPE: 'type',
  MODIFIER: 'modifier',
  DISCOUNT: 'discount',

  IMAGES: 'images',
  IMAGE: 'image',

  CATEGORIES: 'categories',
  CATEGORY: 'textRu',

  RECOMMENDATIONS: 'recommendations',

  PROGRAMS: 'programs',
  PROGRAM_NAME: 'programNameRu',
  PROGRAM_PRICE: 'price',

  MASTER_CLASS: 'masterClassArticle',
};
