import { CREATE_MASTER_CLASS_FIELD_NAME } from './master-class-create.type';

export function convertForUpload(imageUrls, formValues) {
  return {
    [CREATE_MASTER_CLASS_FIELD_NAME.IMAGES]: imageUrls,
    [CREATE_MASTER_CLASS_FIELD_NAME.NAME]:
      formValues[CREATE_MASTER_CLASS_FIELD_NAME.NAME],
    [CREATE_MASTER_CLASS_FIELD_NAME.MODIFIER]:
      formValues[CREATE_MASTER_CLASS_FIELD_NAME.MODIFIER],
    [CREATE_MASTER_CLASS_FIELD_NAME.CATEGORIES]: formValues[
      CREATE_MASTER_CLASS_FIELD_NAME.CATEGORIES
    ].map((item) => ({
      id: item.basicId,
    })),
    [CREATE_MASTER_CLASS_FIELD_NAME.DESCRIPTION]:
      formValues[CREATE_MASTER_CLASS_FIELD_NAME.DESCRIPTION],
    [CREATE_MASTER_CLASS_FIELD_NAME.ARTICLE]:
      formValues[CREATE_MASTER_CLASS_FIELD_NAME.ARTICLE],
    [CREATE_MASTER_CLASS_FIELD_NAME.DISCOUNT]:
      formValues[CREATE_MASTER_CLASS_FIELD_NAME.DISCOUNT],
    [CREATE_MASTER_CLASS_FIELD_NAME.PRICE]:
      formValues[CREATE_MASTER_CLASS_FIELD_NAME.PRICE],
    [CREATE_MASTER_CLASS_FIELD_NAME.RECOMMENDATIONS]: {
      recommendationProducts:
        formValues[CREATE_MASTER_CLASS_FIELD_NAME.RECOMMENDATIONS],
    },
  };
}
