export const CREATE_MASTER_CLASS_ACTION_TYPE = {
  CREATE_MASTER_CLASS_UPLOAD_PENDING:
    'CREATE_MASTER_CLASS_ACTION_TYPE.CREATE_PRODUCT_UPLOAD_PENDING',
  CREATE_MASTER_CLASS_UPLOAD_SUCCESS:
    'CREATE_MASTER_CLASS_ACTION_TYPE.CREATE_PRODUCT_UPLOAD_SUCCESS',
  CREATE_MASTER_CLASS_UPLOAD_ERROR:
    'CREATE_MASTER_CLASS_ACTION_TYPE.CREATE_PRODUCT_UPLOAD_ERROR',

  MASTER_CLASS_LOAD_PENDING:
    'CREATE_MASTER_CLASS_ACTION_TYPE.MASTER_CLASS_LOAD_PENDING',
  MASTER_CLASS_LOAD_SUCCESS:
    'CREATE_MASTER_CLASS_ACTION_TYPE.MASTER_CLASS_LOAD_SUCCESS',
  MASTER_CLASS_LOAD_ERROR:
    'CREATE_MASTER_CLASS_ACTION_TYPE.MASTER_CLASS_LOAD_ERROR',

  MASTER_CLASS_UPDATE_PENDING:
    'CREATE_MASTER_CLASS_ACTION_TYPE.MASTER_CLASS_UPDATE_PENDING',
  MASTER_CLASS_UPDATE_SUCCESS:
    'CREATE_MASTER_CLASS_ACTION_TYPE.MASTER_CLASS_UPDATE_SUCCESS',
  MASTER_CLASS_UPDATE_ERROR:
    'CREATE_MASTER_CLASS_ACTION_TYPE.MASTER_CLASS_UPDATE_ERROR',

  MASTER_CLASS_DELETE_PENDING:
    'CREATE_MASTER_CLASS_ACTION_TYPE.MASTER_CLASS_DELETE_PENDING',
  MASTER_CLASS_DELETE_SUCCESS:
    'CREATE_MASTER_CLASS_ACTION_TYPE.MASTER_CLASS_DELETE_SUCCESS',
  MASTER_CLASS_DELETE_ERROR:
    'CREATE_MASTER_CLASS_ACTION_TYPE.MASTER_CLASS_DELETE_ERROR',
};

export const CREATE_MASTER_CLASS_FIELD_NAME = {
  NAME: 'titleRu',
  DESCRIPTION: 'descriptionRu',
  MODIFIER: 'modifierRu',
  DISCOUNT: 'discount',
  PRICE: 'price',

  IMAGES: 'images',
  IMAGE: 'image',

  RECOMMENDATIONS: 'recommendation',
  CATEGORIES: 'categories',

  ARTICLE: 'articleRu',
  MATERIAL: 'materialRu',
  DELETED: 'deleted',
};
