export const CREATE_MASTER_CLASS_ACTION_TYPE = {
  CREATE_MASTER_CLASS_UPLOAD_PENDING:
    'CREATE_MASTER_CLASS_ACTION_TYPE.CREATE_PRODUCT_UPLOAD_PENDING',
  CREATE_MASTER_CLASS_UPLOAD_SUCCESS:
    'CREATE_MASTER_CLASS_ACTION_TYPE.CREATE_PRODUCT_UPLOAD_SUCCESS',
  CREATE_MASTER_CLASS_UPLOAD_ERROR:
    'CREATE_MASTER_CLASS_ACTION_TYPE.CREATE_PRODUCT_UPLOAD_ERROR',
};

export const CREATE_MASTER_CLASS_FIELD_NAME = {
  NAME: 'titleRu',
  DESCRIPTION: 'descriptionRu',
  MODIFIER: 'modifierRu',
  DISCOUNT: 'discount',
  PRICE: 'price',

  IMAGES: 'images',
  IMAGE: 'image',

  RECOMMENDATIONS: 'recommendation',
  CATEGORIES: 'categories',

  ARTICLE: 'articleRu',
};
