export const SLIDER_DATA_NAME = {
  BUTTON: 'buttonText',
  TITLE: 'headingText',
  IMAGE_URL: 'imageUrl',
  BUTTON_URL: 'buttonUrl',
};

export const SLIDER_DATA_KEY = {
  BUTTON: 'BUTTON',
  TITLE: 'TITLE',
  IMAGE_URL: 'IMAGE_URL',
  BUTTON_URL: 'BUTTON_URL',
};

export const SLIDER_ACTION_TYPE = {
  SLIDER_LOAD_REQUEST_PENDING: 'SLIDER_ACTION_TYPE.SLIDER_LOAD_REQUEST_PENDING',
  SLIDER_LOAD_REQUEST_SUCCESS: 'SLIDER_ACTION_TYPE.SLIDER_LOAD_REQUEST_SUCCESS',
  SLIDER_LOAD_REQUEST_ERROR: 'SLIDER_ACTION_TYPE.SLIDER_LOAD_REQUEST_ERROR',
};
