export const USERS_ACTION_TYPE = {
  USERS_UPLOAD_PENDING: 'USERS_ACTION_TYPE.USERS_UPLOAD_PENDING',
  USERS_UPLOAD_SUCCESS: 'USERS_ACTION_TYPE.USERS_UPLOAD_SUCCESS',
  USERS_UPLOAD_ERROR: 'USERS_ACTION_TYPE.USERS_UPLOAD_ERROR',
};
