export const FIND_ADRESS_ACTION_TYPE = {
  FIND_COUNTRY_PENDING: 'FIND_ADRESS_ACTION_TYPE.FIND_COUNTRY_PENDING',
  FIND_COUNTRY_SUCCESS: 'FIND_ADRESS_ACTION_TYPE.FIND_COUNTRY_SUCCESS',
  FIND_COUNTRY_ERROR: 'FIND_ADRESS_ACTION_TYPE.FIND_COUNTRY_ERROR',

  FIND_REGION_PENDING: 'FIND_ADRESS_ACTION_TYPE.FIND_REGION_PENDING',
  FIND_REGION_SUCCESS: 'FIND_ADRESS_ACTION_TYPE.FIND_REGION_SUCCESS',
  FIND_REGION_ERROR: 'FIND_ADRESS_ACTION_TYPE.FIND_REGION_ERROR',

  FIND_CITY_PENDING: 'FIND_ADRESS_ACTION_TYPE.FIND_CITY_PENDING',
  FIND_CITY_SUCCESS: 'FIND_ADRESS_ACTION_TYPE.FIND_CITY_SUCCESS',
  FIND_CITY_ERROR: 'FIND_ADRESS_ACTION_TYPE.FIND_CITY_ERROR',

  FIND_AREA_PENDING: 'FIND_ADRESS_ACTION_TYPE.FIND_AREA_PENDING',
  FIND_AREA_SUCCESS: 'FIND_ADRESS_ACTION_TYPE.FIND_AREA_SUCCESS',
  FIND_AREA_ERROR: 'FIND_ADRESS_ACTION_TYPE.FIND_AREA_ERROR',

  FIND_SETTLEMENT_PENDING: 'FIND_ADRESS_ACTION_TYPE.FIND_SETTLEMENT_PENDING',
  FIND_SETTLEMENT_SUCCESS: 'FIND_ADRESS_ACTION_TYPE.FIND_SETTLEMENT_SUCCESS',
  FIND_SETTLEMENT_ERROR: 'FIND_ADRESS_ACTION_TYPE.FIND_SETTLEMENT_ERROR',

  FIND_STREET_PENDING: 'FIND_ADRESS_ACTION_TYPE.FIND_STREET_PENDING',
  FIND_STREET_SUCCESS: 'FIND_ADRESS_ACTION_TYPE.FIND_STREET_SUCCESS',
  FIND_STREET_ERROR: 'FIND_ADRESS_ACTION_TYPE.FIND_STREET_ERROR',

  FIND_HOUSE_PENDING: 'FIND_ADRESS_ACTION_TYPE.FIND_HOUSE_PENDING',
  FIND_HOUSE_SUCCESS: 'FIND_ADRESS_ACTION_TYPE.FIND_HOUSE_SUCCESS',
  FIND_HOUSE_ERROR: 'FIND_ADRESS_ACTION_TYPE.FIND_HOUSE_ERROR',
};
export interface FindAdreccContainerProps {
  values: any;
  changePostalCode: Function;
  setFieldValue: Function;
  handleBlur: Function;
}
export interface FindAdreccComponentProps {
  values: any;
  handleChange: Function;
  findCountry: Function;
  findCity: Function;
  findStreet: Function;
  findHouse: Function;
  changePostalCode: Function;
  handleBlur: Function;
}
export const FIND_ADRESS_FIELD_NAME = {
  COUNTRY: 'country',
  CITY: 'city',
  STREET: 'street',
  HOUSE: 'house',
  POSTAL_CODE: 'postal_code',
};
