export const FIND_ADRESS_ACTION_TYPE = {
  FIND_COUNTRY_PENDING: 'FIND_ADRESS_ACTION_TYPE.FIND_COUNTRY_PENDING',
  FIND_COUNTRY_SUCCESS: 'FIND_ADRESS_ACTION_TYPE.FIND_COUNTRY_SUCCESS',
  FIND_COUNTRY_ERROR: 'FIND_ADRESS_ACTION_TYPE.FIND_COUNTRY_ERROR',

  FIND_REGION_PENDING: 'FIND_ADRESS_ACTION_TYPE.FIND_REGION_PENDING',
  FIND_REGION_SUCCESS: 'FIND_ADRESS_ACTION_TYPE.FIND_REGION_SUCCESS',
  FIND_REGION_ERROR: 'FIND_ADRESS_ACTION_TYPE.FIND_REGION_ERROR',

  FIND_CITY_PENDING: 'FIND_ADRESS_ACTION_TYPE.FIND_CITY_PENDING',
  FIND_CITY_SUCCESS: 'FIND_ADRESS_ACTION_TYPE.FIND_CITY_SUCCESS',
  FIND_CITY_ERROR: 'FIND_ADRESS_ACTION_TYPE.FIND_CITY_ERROR',

  FIND_AREA_PENDING: 'FIND_ADRESS_ACTION_TYPE.FIND_AREA_PENDING',
  FIND_AREA_SUCCESS: 'FIND_ADRESS_ACTION_TYPE.FIND_AREA_SUCCESS',
  FIND_AREA_ERROR: 'FIND_ADRESS_ACTION_TYPE.FIND_AREA_ERROR',

  FIND_SETTLEMENT_PENDING: 'FIND_ADRESS_ACTION_TYPE.FIND_SETTLEMENT_PENDING',
  FIND_SETTLEMENT_SUCCESS: 'FIND_ADRESS_ACTION_TYPE.FIND_SETTLEMENT_SUCCESS',
  FIND_SETTLEMENT_ERROR: 'FIND_ADRESS_ACTION_TYPE.FIND_SETTLEMENT_ERROR',

  FIND_STREET_PENDING: 'FIND_ADRESS_ACTION_TYPE.FIND_STREET_PENDING',
  FIND_STREET_SUCCESS: 'FIND_ADRESS_ACTION_TYPE.FIND_STREET_SUCCESS',
  FIND_STREET_ERROR: 'FIND_ADRESS_ACTION_TYPE.FIND_STREET_ERROR',

  FIND_HOUSE_PENDING: 'FIND_ADRESS_ACTION_TYPE.FIND_HOUSE_PENDING',
  FIND_HOUSE_SUCCESS: 'FIND_ADRESS_ACTION_TYPE.FIND_HOUSE_SUCCESS',
  FIND_HOUSE_ERROR: 'FIND_ADRESS_ACTION_TYPE.FIND_HOUSE_ERROR',
};
export interface FindAdreccContainerProps {
  values: {
    country: string;
    region: string;
    city: string;
    area: string;
    settlement: string;
    street: string;
    house: string;
  };
  handleChange: Function;
  handleBlur: Function;
  setFieldValue: Function;
}
export interface FindAdreccComponentProps {
  handleChange: Function;
  handleBlur: Function;
  setFieldValue: Function;
}
export enum FIND_ADRESS_FIELD_NAME {
  COUNTRY = 'country',
  REGION = 'region',
  CITY = 'city',
  AREA = 'area',
  SETTLEMENT = 'settlement',
  STREET = 'street',
  HOUSE = 'house',
}
