export const FIND_ADRESS_ACTION_TYPE = {
  FIND_ADRESS_PENDING: 'CATEGORIES_ACTION_TYPE.FIND_ADRESS_PENDING',
  FIND_ADRESS_SUCCESS: 'CATEGORIES_ACTION_TYPE.FIND_ADRESS_SUCCESS',
  FIND_ADRESS_ERROR: 'CATEGORIES_ACTION_TYPE.FIND_ADRESS_ERROR',
};
