export const USERS_ORDER_ACTION_TYPE = {
  USERS_ORDER_UPLOAD_PENDING: 'USERS_ORDER_ACTION_TYPE.USERS_ORDER_UPLOAD_PENDING',
  USERS_ORDER_UPLOAD_SUCCESS: 'USERS_ORDER_ACTION_TYPE.USERS_ORDER_UPLOAD_SUCCESS',
  USERS_ORDER_UPLOAD_ERROR: 'USERS_ORDER_ACTION_TYPE.USERS_ORDER_UPLOAD_ERROR',
};
