export enum CART_ACTION_TYPE {
  ADD_PRODUCT_PENDING = 'CART_ACTION_TYPE.ADD_PRODUCT_PENDING',
  ADD_PRODUCT_SUCCESS = 'CART_ACTION_TYPE.ADD_PRODUCT_SUCCESS',
  ADD_PRODUCT_ERROR = 'CART_ACTION_TYPE.ADD_PRODUCT_ERROR',

  GET_BASKET_PENDING = 'CART_ACTION_TYPE.GET_BASKET_PENDING',
  GET_BASKET_SUCCESS = 'CART_ACTION_TYPE.GET_BASKET_SUCCESS',
  GET_BASKET_ERROR = 'CART_ACTION_TYPE.GET_BASKET_ERROR',

  CHANGE_PRODUCT_PENDING = 'CART_ACTION_TYPE.CHANGE_PRODUCT_PENDING',
  CHANGE_PRODUCT_SUCCESS = 'CART_ACTION_TYPE.CHANGE_PRODUCT_SUCCESS',
  CHANGE_PRODUCT_ERROR = 'CART_ACTION_TYPE.CHANGE_PRODUCT_ERROR',

  DELETE_PRODUCT_PENDING = 'CART_ACTION_TYPE.DELETE_PRODUCT_PENDING',
  DELETE_PRODUCT_SUCCESS = 'CART_ACTION_TYPE.DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCT_ERROR = 'CART_ACTION_TYPE.DELETE_PRODUCT_ERROR',
}

export const CART_API = {
  ADD_PRODUCT: { ENDPOINT: 'basket/create', TYPE: 'POST' },
  GET_BASKET: { ENDPOINT: 'basket/get', TYPE: 'GET' },
  CHANGE_PRODUCT: {
    ENDPOINT: (purchaseProductId: string) =>
      `basket/update/product/${purchaseProductId}`,
    TYPE: 'PATCH',
  },
  DELETE_PRODUCT: {
    ENDPOINT: (purchaseProductId: string) =>
      `basket/delete/product/${purchaseProductId}`,
    TYPE: 'DELETE',
  },
};

export const CART_STORE_NAME = 'CART';
