export enum CART_ACTION_TYPE {
  INCREMENT_SEWING_PRODUCT = 'CART_ACTION_TYPE.INCREMENT_SEWING_PRODUCT',
  INCREMENT_PATTERN_PRODUCT = 'CART_ACTION_TYPE.INCREMENT_PATTERN_PRODUCT',
  INCREMENT_MASTER_CLASS = 'CART_ACTION_TYPE.INCREMENT_MASTER_CLASS',
  DECREMENT_SEWING_PRODUCT = 'CART_ACTION_TYPE.DECREMENT_SEWING_PRODUCT',
  DECREMENT_PATTERN_PRODUCT = 'CART_ACTION_TYPE.DECREMENT_PATTERN_PRODUCT',
  DECREMENT_MASTER_CLASS = 'CART_ACTION_TYPE.DECREMENT_MASTER_CLASS',

  ADD_SEWING_PRODUCT = 'CART_ACTION_TYPE.ADD_SEWING_PRODUCT',
  ADD_PATTERN_PRODUCT = 'CART_ACTION_TYPE.ADD_PATTERN_PRODUCT',
  ADD_MASTER_CLASS = 'CART_ACTION_TYPE.ADD_MASTER_CLASS',

  DELETE_SEWING_PRODUCT = 'CART_ACTION_TYPE.DELETE_SEWING_PRODUCT',
  DELETE_PATTERN_PRODUCT = 'CART_ACTION_TYPE.DELETE_PATTERN_PRODUCT',
  DELETE_MASTER_CLASS = 'CART_ACTION_TYPE.DELETE_MASTER_CLASS',

  CHANGE_SEWING_PRODUCT_PARAMETRS = 'CART_ACTION_TYPE.CHANGE_SEWING_PRODUCT_PARAMETRS',
  CHANGE_PATTERN_PRODUCT_PARAMETRS = 'CART_ACTION_TYPE.CHANGE_PATTERN_PRODUCT_PARAMETRS',
  CHANGE_MASTER_CLASS_PARAMETRS = 'CART_ACTION_TYPE.CHANGE_MASTER_CLASS_PARAMETRS',

  PURGE = 'CART_ACTION_TYPE.PURGE',
}

export const CART_STORE_NAME = 'CART';
