export const ORDERS_ACTION_TYPE = {
  RESET_PRODUCTS_STATE: 'ALL_PRODUCTS_ACTION_TYPE.RESET_PRODUCTS_STATE',
  ORDERS_UPLOAD_PENDING: 'ORDERS_ACTION_TYPE.ORDERS_UPLOAD_PENDING',
  ORDERS_UPLOAD_SUCCESS: 'ORDERS_ACTION_TYPE.ORDERS_UPLOAD_SUCCESS',
  ORDERS_UPLOAD_ERROR: 'ORDERS_ACTION_TYPE.ORDERS_UPLOAD_ERROR',
};
