export const PROMOCODES_FIELD_NAME = {
  CATEGORY: 'category',
  TAGS: 'tags',
  FIND_INPUT: 'find-promocodes',
};

export const PROMOCODES_ACTION_TYPE = {
  PROMOCODES_UPLOAD_PENDING:
    'PROMOCODES_ACTION_TYPE.PROMOCODES_UPLOAD_PENDING',
  PROMOCODES_UPLOAD_SUCCESS:
    'PROMOCODES_ACTION_TYPE.PROMOCODES_UPLOAD_SUCCESS',
  PROMOCODES_UPLOAD_ERROR:
    'PROMOCODES_ACTION_TYPE.PROMOCODES_UPLOAD_ERROR',
};
