export const HOME_ACTION_TYPE = {
  HOME_MASTER_CLASS_PENDING: 'HOME_ACTION_TYPE.HOME_MASTER_CLASS_PENDING',
  HOME_MASTER_CLASS_SUCCESS: 'HOME_ACTION_TYPE.HOME_MASTER_CLASS_SUCCESS',
  HOME_MASTER_CLASS_ERROR: 'HOME_ACTION_TYPE.HOME_MASTER_CLASS_ERROR',
  HOME_SEWING_GOODS_PENDING: 'HOME_ACTION_TYPE.HOME_SEWING_GOODS_PENDING',
  HOME_SEWING_GOODS_SUCCESS: 'HOME_ACTION_TYPE.HOME_SEWING_GOODS_SUCCESS',
  HOME_SEWING_GOODS_ERROR: 'HOME_ACTION_TYPE.HOME_SEWING_GOODS_ERROR',
  HOME_ARTICLE_PENDING: 'HOME_ACTION_TYPE.HOME_ARTICLE_PENDING',
  HOME_ARTICLE_SUCCESS: 'HOME_ACTION_TYPE.HOME_ARTICLE_SUCCESS',
  HOME_ARTICLE_ERROR: 'HOME_ACTION_TYPE.HOME_ARTICLE_ERROR',
};
