export const HOME_ACTION_TYPE = {
  HOME_COMPILATION_LOAD_PENDING:
    'HOME_ACTION_TYPE.HOME_COMPILATION_LOAD_PENDING',
  HOME_COMPILATION_LOAD_SUCCESS:
    'HOME_ACTION_TYPE.HOME_COMPILATION_LOAD_SUCCESS',
  HOME_COMPILATION_LOAD_ERROR: 'HOME_ACTION_TYPE.HOME_COMPILATION_LOAD_ERROR',
};
