export const CREATE_PATTERN_ACTION_TYPE = {
  CREATE_PATTERN_UPLOAD_PENDING:
    'CREATE_PATTERN_ACTION_TYPE.CREATE_PATTERN_UPLOAD_PENDING',
  CREATE_PATTERN_UPLOAD_SUCCESS:
    'CREATE_PATTERN_ACTION_TYPE.CREATE_PATTERN_UPLOAD_SUCCESS',
  CREATE_PATTERN_UPLOAD_ERROR:
    'CREATE_PATTERN_ACTION_TYPE.CREATE_PATTERN_UPLOAD_ERROR',

  PATTERN_PRODUCT_LOAD_PENDING:
    'CREATE_PATTERN_ACTION_TYPE.PATTERN_PRODUCT_LOAD_PENDING',
  PATTERN_PRODUCT_LOAD_SUCCESS:
    'CREATE_PATTERN_ACTION_TYPE.PATTERN_PRODUCT_LOAD_SUCCESS',
  PATTERN_PRODUCT_LOAD_ERROR:
    'CREATE_PATTERN_ACTION_TYPE.PATTERN_PRODUCT_LOAD_ERROR',

  PATTERN_PRODUCT_UPDATE_PENDING:
    'CREATE_PATTERN_ACTION_TYPE.PATTERN_PRODUCT_UPDATE_PENDING',
  PATTERN_PRODUCT_UPDATE_SUCCESS:
    'CREATE_PATTERN_ACTION_TYPE.PATTERN_PRODUCT_UPDATE_SUCCESS',
  PATTERN_PRODUCT_UPDATE_ERROR:
    'CREATE_PATTERN_ACTION_TYPE.PATTERN_PRODUCT_UPDATE_ERROR',

  PATTERN_PRODUCT_DELETE_PENDING:
    'CREATE_MASTER_CLASS_ACTION_TYPE.PATTERN_PRODUCT_DELETE_PENDING',
  PATTERN_PRODUCT_DELETE_SUCCESS:
    'CREATE_MASTER_CLASS_ACTION_TYPE.PATTERN_PRODUCT_DELETE_SUCCESS',
  PATTERN_PRODUCT_DELETE_ERROR:
    'CREATE_MASTER_CLASS_ACTION_TYPE.PATTERN_PRODUCT_DELETE_ERROR',
};

export const CREATE_PATTERN_FIELD_NAME = {
  NAME: 'titleRu',
  VENDOR_CODE: 'vendorCode',
  OPTION_VISIBILITY: 'optionVisibility',
  DESCRIPTION: 'descriptionRu',
  MODIFIER: 'modifierRu',
  MATERIAL: 'materialRu',
  COMPLEXITY: 'complexity',
  IMAGES: 'images',
  IMAGE: 'image',
  RECOMMENDATIONS: 'recommendation',
  CATEGORIES: 'categories',
  TYPE: 'type',

  PRICE: 'price',
  DISCOUNT: 'discount',
  COUNT: 'count',
  IS_COUNT: 'isCount',
  OPTION_TYPE: 'optionType',

  OPTIONS: 'options',
  OPTION_SIZE: 'size',
  OPTION_PRICE: 'price',
  OPTION_DISCOUNT: 'discount',
  OPTION_COUNT: 'count',

  OPTION_FILES: 'filesPdf',
  OPTION_FILE: 'optionFilePdf',

  FILES: 'filesPdf',
  FILE: 'productFilePdf',
  DELETED: 'deleted',
};
