export const MY_PATTERNS_ACTION_TYPE = {
  MY_PATTERNS_UPLOAD_PENDING: 'MY_PATTERNS_ACTION_TYPE.MY_PATTERNS_UPLOAD_PENDING',
  MY_PATTERNS_UPLOAD_SUCCESS: 'MY_PATTERNS_ACTION_TYPE.MY_PATTERNS_UPLOAD_SUCCESS',
  MY_PATTERNS_UPLOAD_ERROR: 'MY_PATTERNS_ACTION_TYPE.MY_PATTERNS_UPLOAD_ERROR',
};
