export const ABOUT_ORDER_FIELD_NAME = {
  ID: 'id',
  CITY: 'city',
  EMAIL: 'email',
  FULL_NAME: 'fullName',
  ORDER_NUMBER: 'orderNumber',
  PHONE_NUMBER: 'phoneNumber',
  ORDER_STATUS: 'orderStatus',
  PRICE: 'price',
  PROMO_CODE: 'promoCode',
  COMMENT: 'comment',
  PROMO_CODE_DISCOUNT: 'promoCodeDiscount',
  DELIVERY_METHOD: 'typeOfDelivery',
  // PAYMENT_METHOD: 'paymentMethod',
};

export const USER_ORDER_ACTION_TYPE = {
  USER_ORDER_UPLOAD_PENDING:
    'USER_ORDER_ACTION_TYPE.USER_ORDER_UPLOAD_PENDING',
  USER_ORDER_UPLOAD_SUCCESS:
    'USER_ORDER_ACTION_TYPE.USER_ORDER_UPLOAD_SUCCESS',
  USER_ORDER_UPLOAD_ERROR:
    'USER_ORDER_ACTION_TYPE.USER_ORDER_UPLOAD_ERROR',
  USER_ORDER_UPDATE_PENDING:
    'USER_ORDER_ACTION_TYPE.USER_ORDER_UPDATE_PENDING',
  USER_ORDER_UPDATE_SUCCESS:
    'USER_ORDER_ACTION_TYPE.USER_ORDER_UPDATE_SUCCESS',
  USER_ORDER_UPDATE_ERROR:
    'USER_ORDER_ACTION_TYPE.USER_ORDER_UPLOAD_ERROR',
};
