export const MY_MASTER_CLASSES_ACTION_TYPE = {
  MY_MASTER_CLASSES_UPLOAD_PENDING: 'MY_MASTER_CLASSES_ACTION_TYPE.MY_MASTER_CLASSES_UPLOAD_PENDING',
  MY_MASTER_CLASSES_UPLOAD_SUCCESS: 'MY_MASTER_CLASSES_ACTION_TYPE.MY_MASTER_CLASSES_UPLOAD_SUCCESS',
  MY_MASTER_CLASSES_UPLOAD_ERROR: 'MY_MASTER_CLASSES_ACTION_TYPE.MY_MASTER_CLASSES_UPLOAD_ERROR',
};
