//КУДА ВЫНЕСТИ ARTICLE_DATA_NAME И ARTICLE_DATA_KEY
export const ARTICLE_DATA_NAME = {
  ID: 'id',
  IMAGE: 'image',
  TITLE: 'title',
  DATE: 'date',
  LIKED: 'liked',
};

export const ARTICLE_DATA_KEY = {
  ID: 'ID',
  IMAGE: 'IMAGE',
  TITLE: 'TITLE',
  DATE: 'DATE',
  LIKED: 'LIKED',
};

export const HOME_ARTICLE_ACTION_TYPE = {
  HOME_ARTICLE_LOAD_PENDING:
    'HOME_ARTICLE_ACTION_TYPE.HOME_ARTICLE_LOAD_PENDING',
  HOME_ARTICLE_LOAD_SUCCESS:
    'HOME_ARTICLE_ACTION_TYPE.HOME_ARTICLE_LOAD_SUCCESS',
  HOME_ARTICLE_LOAD_ERROR: 'HOME_ARTICLE_ACTION_TYPE.HOME_ARTICLE_LOAD_ERROR',
};
