export const MASTER_CLASSES_FIELD_NAME = {
  CATEGORY: 'category',
  TAGS: 'tags',
  FIND_INPUT: 'find-master-classes',
};

export const MASTER_CLASSES_ACTION_TYPE = {
  MASTER_CLASSES_UPLOAD_PENDING:
    'MASTER_CLASSES_ACTION_TYPE.MASTER_CLASSES_UPLOAD_PENDING',
  MASTER_CLASSES_UPLOAD_SUCCESS:
    'MASTER_CLASSES_ACTION_TYPE.MASTER_CLASSES_UPLOAD_SUCCESS',
  MASTER_CLASSES_UPLOAD_ERROR:
    'MASTER_CLASSES_ACTION_TYPE.MASTER_CLASSES_UPLOAD_ERROR',
};
