export const MASTER_CLASSES_ACTION_TYPE = {
  RESET_PRODUCTS_STATE: 'MASTER_CLASSES_ACTION_TYPE.RESET_PRODUCTS_STATE',
  MASTER_CLASSES_UPLOAD_PENDING:
    'MASTER_CLASSES_ACTION_TYPE.MASTER_CLASSES_UPLOAD_PENDING',
  MASTER_CLASSES_UPLOAD_SUCCESS:
    'MASTER_CLASSES_ACTION_TYPE.MASTER_CLASSES_UPLOAD_SUCCESS',
  MASTER_CLASSES_UPLOAD_ERROR:
    'MASTER_CLASSES_ACTION_TYPE.MASTER_CLASSES_UPLOAD_ERROR',
  MASTER_CLASSES_UPDATE_PENDING:
    'MASTER_CLASSES_ACTION_TYPE.MASTER_CLASSES_UPDATE_PENDING',
  MASTER_CLASSES_UPDATE_SUCCESS:
    'MASTER_CLASSES_ACTION_TYPE.MASTER_CLASSES_UPDATE_SUCCESS',
  MASTER_CLASSES_UPDATE_ERROR:
    'MASTER_CLASSES_ACTION_TYPE.MASTER_CLASSES_UPDATE_ERROR',
  CATEGORIES_UPLOAD_PENDING: 'MASTER_CLASSES_ACTION_TYPE.CATEGORIES_UPLOAD_PENDING',
  CATEGORIES_UPLOAD_SUCCESS: 'MASTER_CLASSES_ACTION_TYPE.CATEGORIES_UPLOAD_SUCCESS',
  CATEGORIES_UPLOAD_ERROR: 'MASTER_CLASSES_ACTION_TYPE.CATEGORIES_UPLOAD_ERROR',
};
