export const SEWING_GOODS_PAGE_ACTION_TYPE = {
  SEWING_GOODS_PAGE_UPLOAD_PENDING:
    'SEWING_GOODS_PAGE_ACTION_TYPE.SEWING_GOODS_PAGE_UPLOAD_PENDING',
  SEWING_GOODS_PAGE_UPLOAD_SUCCESS:
    'SEWING_GOODS_PAGE_ACTION_TYPE.SEWING_GOODS_PAGE_UPLOAD_SUCCESS',
  SEWING_GOODS_PAGE_UPLOAD_ERROR:
    'SEWING_GOODS_PAGE_ACTION_TYPE.SEWING_GOODS_PAGE_UPLOAD_ERROR',
};
