export const AUTH_CHANGE_EMAIL_ACTION_TYPE = {
  AUTH_CHANGE_EMAIL_UPLOAD_PENDING:
    'AUTH_CHANGE_EMAIL_ACTION_TYPE.AUTH_CHANGE_EMAIL_UPLOAD_PENDING',
  AUTH_CHANGE_EMAIL_UPLOAD_SUCCESS:
    'AUTH_CHANGE_EMAIL_ACTION_TYPE.AUTH_CHANGE_EMAIL_UPLOAD_SUCCESS',
  AUTH_CHANGE_EMAIL_UPLOAD_ERROR:
    'AUTH_CHANGE_EMAIL_ACTION_TYPE.AUTH_CHANGE_EMAIL_UPLOAD_ERROR',
};
