export const ORDERS_LIST_ACTION_TYPE = {
  ORDERS_LIST_UPLOAD_PENDING: 'ORDERS_LIST_ACTION_TYPE.ORDERS_LIST_UPLOAD_PENDING',
  ORDERS_LIST_UPLOAD_SUCCESS: 'ORDERS_LIST_ACTION_TYPE.ORDERS_LIST_UPLOAD_SUCCESS',
  ORDERS_LIST_UPLOAD_ERROR: 'ORDERS_LIST_ACTION_TYPE.ORDERS_LIST_UPLOAD_ERROR',
};
