export const FEEDBACK_ACTION_TYPE = {
  FEEDBACK_UPLOAD_PENDING: 'FEEDBACK_ACTION_TYPE.FEEDBACK_UPLOAD_PENDING',
  FEEDBACK_UPLOAD_SUCCESS: 'FEEDBACK_ACTION_TYPE.FEEDBACK_UPLOAD_SUCCESS',
  FEEDBACK_UPLOAD_ERROR: 'FEEDBACK_ACTION_TYPE.FEEDBACK_UPLOAD_ERROR',
};

export const FEEDBACK_FIELD_NAME = {
  DESCRIPTION: 'description',
};
