export const STATISTICS_ACTION_TYPE = {
  ORDERS_COUNT_PENDING: 'STATISTICS_ACTION_TYPE.ORDERS_COUNT_PENDING',
  ORDERS_COUNT_SUCCESS: 'STATISTICS_ACTION_TYPE.ORDERS_COUNT_SUCCESS',
  ORDERS_COUNT_ERROR: 'STATISTICS_ACTION_TYPE.ORDERS_COUNT_ERROR',
  PRICE_PENDING: 'STATISTICS_ACTION_TYPE.PRICE_PENDING',
  PRICE_SUCCESS: 'STATISTICS_ACTION_TYPE.PRICE_SUCCESS',
  PRICE_ERROR: 'STATISTICS_ACTION_TYPE.PRICE_ERROR',
};
