export const STATISTICS_ACTION_TYPE = {
  GET_COUNT_PENDING: 'STATISTICS_ACTION_TYPE.GET_COUNT_PENDING',
  GET_COUNT_SUCCESS: 'STATISTICS_ACTION_TYPE.GET_COUNT_SUCCESS',
  GET_COUNT_ERROR: 'STATISTICS_ACTION_TYPE.GET_COUNT_ERROR',

  GET_PRICE_PENDING: 'STATISTICS_ACTION_TYPE.GET_PRICE_PENDING',
  GET_PRICE_SUCCESS: 'STATISTICS_ACTION_TYPE.GET_PRICE_SUCCESS',
  GET_PRICE_ERROR: 'STATISTICS_ACTION_TYPE.GET_PRICE_ERROR',

  GET_GENERAL_PENDING: 'STATISTICS_ACTION_TYPE.GET_GENERAL_PENDING',
  GET_GENERAL_SUCCESS: 'STATISTICS_ACTION_TYPE.GET_GENERAL_SUCCESS',
  GET_GENERAL_ERROR: 'STATISTICS_ACTION_TYPE.GET_GENERAL_ERROR',

  GET_USERS_PENDING: 'STATISTICS_ACTION_TYPE.GET_USERS_PENDING',
  GET_USERS_SUCCESS: 'STATISTICS_ACTION_TYPE.GET_USERS_SUCCESS',
  GET_USERS_ERROR: 'STATISTICS_ACTION_TYPE.GET_USERS_ERROR',
};
