export const STATISTICS_ACTION_TYPE = {
  LOAD_DATA_PENDING: 'STATISTICS_ACTION_TYPE.LOAD_DATA_PENDING',
  LOAD_DATA_SUCCESS: 'STATISTICS_ACTION_TYPE.LOAD_DATA_SUCCESS',
  LOAD_DATA_ERROR: 'STATISTICS_ACTION_TYPE.LOAD_DATA_ERROR',
};
