export const SEWING_GOODS_PRODUCT_ACTION_TYPE = {
  SEWING_GOODS_PRODUCT_UPLOAD_PENDING:
    'SEWING_GOODS_PRODUCT_ACTION_TYPE.SEWING_GOODS_PRODUCT_UPLOAD_PENDING',
  SEWING_GOODS_PRODUCT_UPLOAD_SUCCESS:
    'SEWING_GOODS_PRODUCT_ACTION_TYPE.SEWING_GOODS_PRODUCT_UPLOAD_SUCCESS',
  SEWING_GOODS_PRODUCT_UPLOAD_ERROR:
    'SEWING_GOODS_PRODUCT_ACTION_TYPE.SEWING_GOODS_PRODUCT_UPLOAD_ERROR',
};
