export const CREATE_ELECTRONIC_PATTERN_TYPE = {
  CREATE_ELECTRONIC_PATTERN_UPLOAD_PENDING:
    'CREATE_ELECTRONIC_PATTERN_TYPE.CREATE_ELECTRONIC_PATTERN_UPLOAD_PENDING',
  CREATE_ELECTRONIC_PATTERN_UPLOAD_SUCCESS:
    'CREATE_ELECTRONIC_PATTERN_TYPE.CREATE_ELECTRONIC_PATTERN_UPLOAD_SUCCESS',
  CREATE_ELECTRONIC_PATTERN_UPLOAD_ERROR:
    'CREATE_ELECTRONIC_PATTERN_TYPE.CREATE_ELECTRONIC_PATTERN_UPLOAD_ERROR',
};

export const ELECTRONIC_PATTERN_FIELD_NAME = {
  NAME: 'titleRu',
  DESCRIPTION: 'descriptionRu',
  TYPE: 'type',
  MODIFIER: 'modifier',
  DISCOUNT: 'discount',

  MATERIAL: 'materialRu',
  COMPLEXITY: 'complexity',
  PRICE: 'price',
  FILE: 'file',

  IMAGES: 'images',
  IMAGE: 'image',

  CATEGORIES: 'categories',
  CATEGORY: 'textRu',

  RECOMENDATIONS: 'recomendations',
  RECOMENDATION_NAME: 'recomendation',
};
