import { ELECTRONIC_PATTERN_FIELD_NAME } from './patterns-create-electronic.type';

export function convertForUpload(imageUrls, pdfFilesUrls, formValues) {
  return {
    [ELECTRONIC_PATTERN_FIELD_NAME.IMAGES]: imageUrls,
    [ELECTRONIC_PATTERN_FIELD_NAME.NAME]:
      formValues[ELECTRONIC_PATTERN_FIELD_NAME.NAME],
    [ELECTRONIC_PATTERN_FIELD_NAME.MODIFIER]:
      formValues[ELECTRONIC_PATTERN_FIELD_NAME.MODIFIER],
    [ELECTRONIC_PATTERN_FIELD_NAME.CATEGORIES]: formValues[
      ELECTRONIC_PATTERN_FIELD_NAME.CATEGORIES
    ].map((item) => ({ [ELECTRONIC_PATTERN_FIELD_NAME.CATEGORY]: item })),
    [ELECTRONIC_PATTERN_FIELD_NAME.DESCRIPTION]:
      formValues[ELECTRONIC_PATTERN_FIELD_NAME.DESCRIPTION],
    [ELECTRONIC_PATTERN_FIELD_NAME.MATERIAL]:
      formValues[ELECTRONIC_PATTERN_FIELD_NAME.MATERIAL],
    [ELECTRONIC_PATTERN_FIELD_NAME.COMPLEXITY]:
      formValues[ELECTRONIC_PATTERN_FIELD_NAME.COMPLEXITY],
    [ELECTRONIC_PATTERN_FIELD_NAME.DISCOUNT]:
      formValues[ELECTRONIC_PATTERN_FIELD_NAME.DISCOUNT],
    [ELECTRONIC_PATTERN_FIELD_NAME.TYPE]: 1,
    [ELECTRONIC_PATTERN_FIELD_NAME.SIZES]: formValues[
      ELECTRONIC_PATTERN_FIELD_NAME.SIZES
    ].map((item, index) => {
      item[ELECTRONIC_PATTERN_FIELD_NAME.FILE] = pdfFilesUrls[index];
      return item;
    }),
  };
}

export function convertForPreUploadPDFFiles(data) {
  return data.map((item) => item[ELECTRONIC_PATTERN_FIELD_NAME.FILE]);
}
