import { ELECTRONIC_PATTERN_FIELD_NAME } from './patterns-create-electronic.type';

export function convertForUpload(imageUrls, pdfFileUrl, formValues) {
  return {
    [ELECTRONIC_PATTERN_FIELD_NAME.IMAGES]: imageUrls,
    [ELECTRONIC_PATTERN_FIELD_NAME.NAME]:
      formValues[ELECTRONIC_PATTERN_FIELD_NAME.NAME],
    [ELECTRONIC_PATTERN_FIELD_NAME.MODIFIER]:
      formValues[ELECTRONIC_PATTERN_FIELD_NAME.MODIFIER],
    [ELECTRONIC_PATTERN_FIELD_NAME.CATEGORIES]: formValues[
      ELECTRONIC_PATTERN_FIELD_NAME.CATEGORIES
    ].map((item) => ({ [ELECTRONIC_PATTERN_FIELD_NAME.CATEGORY]: item })),
    [ELECTRONIC_PATTERN_FIELD_NAME.DESCRIPTION]:
      formValues[ELECTRONIC_PATTERN_FIELD_NAME.DESCRIPTION],
    [ELECTRONIC_PATTERN_FIELD_NAME.MATERIAL]:
      formValues[ELECTRONIC_PATTERN_FIELD_NAME.MATERIAL],
    [ELECTRONIC_PATTERN_FIELD_NAME.COMPLEXITY]:
      formValues[ELECTRONIC_PATTERN_FIELD_NAME.COMPLEXITY],
    [ELECTRONIC_PATTERN_FIELD_NAME.DISCOUNT]:
      formValues[ELECTRONIC_PATTERN_FIELD_NAME.DISCOUNT],
    [ELECTRONIC_PATTERN_FIELD_NAME.FILE]: pdfFileUrl,
    [ELECTRONIC_PATTERN_FIELD_NAME.PRICE]:
      formValues[ELECTRONIC_PATTERN_FIELD_NAME.PRICE],
    [ELECTRONIC_PATTERN_FIELD_NAME.TYPE]: 1,
  };
}
