export const SLIDER_EDIT_ACTION_TYPE = {
  SLIDER_EDIT_UPLOAD_PENDING: 'SLIDER_EDIT_ACTION_TYPE.SLIDER_EDIT_UPLOAD_PENDING',
  SLIDER_EDIT_UPLOAD_SUCCESS: 'SLIDER_EDIT_ACTION_TYPE.SLIDER_EDIT_UPLOAD_SUCCESS',
  SLIDER_EDIT_UPLOAD_ERROR: 'SLIDER_EDIT_ACTION_TYPE.SLIDER_EDIT_UPLOAD_ERROR',
};
