export const SLIDER_EDIT_ACTION_TYPE = {
  SLIDER_EDIT_UPLOAD_PENDING:
    'SLIDER_EDIT_ACTION_TYPE.SLIDER_EDIT_UPLOAD_PENDING',
  SLIDER_EDIT_UPLOAD_SUCCESS:
    'SLIDER_EDIT_ACTION_TYPE.SLIDER_EDIT_UPLOAD_SUCCESS',
  SLIDER_EDIT_UPLOAD_ERROR: 'SLIDER_EDIT_ACTION_TYPE.SLIDER_EDIT_UPLOAD_ERROR',
};
export const SLIDER_EDIT_FIELD_NAME = {
  TITLE_TEXT: 'titleText',
  BUTTON_TEXT: 'buttonText',
  TITLE_TEXT_COLOR: 'titleTextColor',
  BUTTON_TEXT_COLOR: 'buttonTextColor',
  BUTTON_COLOR: 'buttonColor',
  IS_BUTTON: 'isButton',
  BUTTON_PATH: 'buttonPath',
};
