export const THEME_COLOR = {
  BACKGROUND_GRAY: '#f0f0f0',
  BACKGROUND_DANGER: '#ffeaea',

  TEXT_PRIMARY: '#2f2a2c',
  TEXT_SECONDARY: '#5f5b5d',
  TEXT_DANGER: '#eb5757',

  BUTTON_PRIMARY: '#ff005a',
  BUTTON_TEXT_PRIMARY: '#fff',

  FIELD_PRIMARY: '#8f8d8e',
  FIELD_STROKE_PRIMARY: '#bfbfbf',
};
