import { SETTINGS_FORM_CHANGE_DELIVERY_INFO_FIELD_KEY } from './frames/settings-form-change-delivery-info';

export const SETTINGS_CHANGE_DELIVERY_INFO_FIELD_NAME = {
  FULLNAME: 'fullName',
  PHONE: 'phone',
  LOCATION: 'location',
  DELIVERY_TYPE: 'deliveryType',
};

export const SETTINGS_CHANGE_DELIVERY_INFO_FORM_FIELD_NAME = {
  [SETTINGS_FORM_CHANGE_DELIVERY_INFO_FIELD_KEY.FULLNAME]:
    SETTINGS_CHANGE_DELIVERY_INFO_FIELD_NAME.FULLNAME,
  [SETTINGS_FORM_CHANGE_DELIVERY_INFO_FIELD_KEY.PHONE]:
    SETTINGS_CHANGE_DELIVERY_INFO_FIELD_NAME.PHONE,
  [SETTINGS_FORM_CHANGE_DELIVERY_INFO_FIELD_KEY.LOCATION]:
    SETTINGS_CHANGE_DELIVERY_INFO_FIELD_NAME.LOCATION,
  [SETTINGS_FORM_CHANGE_DELIVERY_INFO_FIELD_KEY.DELIVERY_TYPE]:
    SETTINGS_CHANGE_DELIVERY_INFO_FIELD_NAME.DELIVERY_TYPE,
};

export const SETTINGS_CHANGE_DELIVERY_INFO_DATA_NAME = {
  FULLNAME: 'fullName',
  PHONE: 'phone',
  LOCATION: 'location',
  DELIVERY_TYPE: 'deliveryType',
};

export const SETTINGS_CHANGE_DELIVERY_INFO_ACTION_TYPE = {
  SETTINGS_CHANGE_DELIVERY_INFO_DATA_LOAD_PENDING:
    'SETTINGS_CHANGE_DELIVERY_INFO_ACTION_TYPE.SETTINGS_CHANGE_DELIVERY_INFO_DATA_LOAD_PENDING',
  SETTINGS_CHANGE_DELIVERY_INFO_DATA_LOAD_SUCCESS:
    'SETTINGS_CHANGE_DELIVERY_INFO_ACTION_TYPE.SETTINGS_CHANGE_DELIVERY_INFO_DATA_LOAD_SUCCESS',
  SETTINGS_CHANGE_DELIVERY_INFO_DATA_LOAD_ERROR:
    'SETTINGS_CHANGE_DELIVERY_INFO_ACTION_TYPE.SETTINGS_CHANGE_DELIVERY_INFO_DATA_LOAD_ERROR',
  SETTINGS_CHANGE_DELIVERY_INFO_FORM_UPLOAD_PENDING:
    'SETTINGS_CHANGE_DELIVERY_INFO_ACTION_TYPE.SETTINGS_CHANGE_DELIVERY_INFO_FORM_UPLOAD_PENDING',
  SETTINGS_CHANGE_DELIVERY_INFO_FORM_UPLOAD_SUCCESS:
    'SETTINGS_CHANGE_DELIVERY_INFO_ACTION_TYPE.SETTINGS_CHANGE_DELIVERY_INFO_FORM_UPLOAD_SUCCESS',
  SETTINGS_CHANGE_DELIVERY_INFO_FORM_UPLOAD_ERROR:
    'SETTINGS_CHANGE_DELIVERY_INFO_ACTION_TYPE.SETTINGS_CHANGE_DELIVERY_INFO_FORM_UPLOAD_ERROR',
  SETTINGS_GET_DELIVERY_TYPES_LOAD_PENDING:
    'SETTINGS_CHANGE_DELIVERY_INFO_ACTION_TYPE.SETTINGS_GET_DELIVERY_TYPES_LOAD_PENDING',
  SETTINGS_GET_DELIVERY_TYPES_LOAD_SUCCESS:
    'SETTINGS_CHANGE_DELIVERY_INFO_ACTION_TYPE.SETTINGS_GET_DELIVERY_TYPES_LOAD_SUCCESS',
  SETTINGS_GET_DELIVERY_TYPES_LOAD_ERROR:
    'SETTINGS_CHANGE_DELIVERY_INFO_ACTION_TYPE.SETTINGS_GET_DELIVERY_TYPES_LOAD_ERROR',
};
