export const SLIDER_LIST_FIELD_NAME = {
  CATEGORY: 'category',
  TAGS: 'tags',
  FIND_INPUT: 'find-input-slider-list',
};

export const SLIDER_LIST_ACTION_TYPE = {
  SLIDER_LIST_UPLOAD_PENDING: 'SLIDER_LIST_ACTION_TYPE.SLIDER_LIST_UPLOAD_PENDING',
  SLIDER_LIST_UPLOAD_SUCCESS: 'SLIDER_LIST_ACTION_TYPE.SLIDER_LIST_UPLOAD_SUCCESS',
  SLIDER_LIST_UPLOAD_ERROR: 'SLIDER_LIST_ACTION_TYPE.SLIDER_LIST_UPLOAD_ERROR',
  CREATE_SLIDER: 'SLIDER_LIST_ACTION_TYPE.ADD_SLIDER',
  REMOVE_SLIDER: 'SLIDER_LIST_ACTION_TYPE.REMOVE_SLIDER',
};
