export const NOTIFICATION_ACTION_TYPE = {
  NOTIFICATION_FORM_UPLOAD_PENDING:
    'NOTIFICATION_ACTION_TYPE.NOTIFICATION_FORM_UPLOAD_PENDING',
  NOTIFICATION_FORM_UPLOAD_SUCCESS:
    'NOTIFICATION_ACTION_TYPE.NOTIFICATION_FORM_UPLOAD_SUCCESS',
  NOTIFICATION_FORM_UPLOAD_ERROR:
    'NOTIFICATION_ACTION_TYPE.NOTIFICATION_FORM_UPLOAD_ERROR',

  GET_NOTIFICATION_STATUS_PENDING:
    'NOTIFICATION_ACTION_TYPE.GET_NOTIFICATION_STATUS_PENDING',
  GET_NOTIFICATION_STATUS_SUCCESS:
    'NOTIFICATION_ACTION_TYPE.GET_NOTIFICATION_STATUS_SUCCESS',
  GET_NOTIFICATION_STATUS_ERROR:
    'NOTIFICATION_ACTION_TYPE.GET_NOTIFICATION_STATUS_ERROR',
};
