import { NOTIFICATION_FORM_FIELD_KEY } from './frames/notification-form';

export const NOTIFICATION_FIELD_NAME = {
  EMAIL: 'email',
};

export const NOTIFICATION_FORM_FIELD_NAME = {
  [NOTIFICATION_FORM_FIELD_KEY.EMAIL]: NOTIFICATION_FIELD_NAME.EMAIL,
};

export const NOTIFICATION_DATA_NAME = {
  EMAIL: 'email',
};

export const NOTIFICATION_DATA_KEY = {
  EMAIL: 'EMAIL',
};

export const NOTIFICATION_ACTION_TYPE = {
  NOTIFICATION_FORM_UPLOAD_PENDING:
    'NOTIFICATION_ACTION_TYPE.NOTIFICATION_FORM_UPLOAD_PENDING',
  NOTIFICATION_FORM_UPLOAD_SUCCESS:
    'NOTIFICATION_ACTION_TYPE.NOTIFICATION_FORM_UPLOAD_SUCCESS',
  NOTIFICATION_FORM_UPLOAD_ERROR:
    'NOTIFICATION_ACTION_TYPE.NOTIFICATION_FORM_UPLOAD_ERROR',

  NOTIFICATION_LOAD_EMAIL_PENDING:
    'NOTIFICATION_ACTION_TYPE.NOTIFICATION_LOAD_EMAIL_PENDING',
  NOTIFICATION_LOAD_EMAIL_SUCCESS:
    'NOTIFICATION_ACTION_TYPE.NOTIFICATION_LOAD_EMAIL_SUCCESS',
  NOTIFICATION_LOAD_EMAIL_ERROR:
    'NOTIFICATION_ACTION_TYPE.NOTIFICATION_LOAD_EMAIL_ERROR',
};
