import { SETTINGS_FORM_CHANGE_PASSWORD_FIELD_KEY } from './frames/settings-form-change-password';

export const SETTINGS_CHANGE_PASSWORD_FIELD_NAME = {
  OLD_PASSWORD: 'oldPassword',
  PASSWORD: 'password',
  PASSWORD_REPEAT: 'passwordRepeat',
};

export const SETTINGS_CHANGE_PASSWORD_FORM_FIELD_NAME = {
  [SETTINGS_FORM_CHANGE_PASSWORD_FIELD_KEY.OLD_PASSWORD]:
    SETTINGS_CHANGE_PASSWORD_FIELD_NAME.OLD_PASSWORD,
  [SETTINGS_FORM_CHANGE_PASSWORD_FIELD_KEY.PASSWORD]:
    SETTINGS_CHANGE_PASSWORD_FIELD_NAME.PASSWORD,
  [SETTINGS_FORM_CHANGE_PASSWORD_FIELD_KEY.PASSWORD_REPEAT]:
    SETTINGS_CHANGE_PASSWORD_FIELD_NAME.PASSWORD_REPEAT,
};

export const SETTINGS_CHANGE_PASSWORD_DATA_NAME = {
  OLD_PASSWORD: 'password',
  PASSWORD: 'newPassword',
};

export const SETTINGS_CHANGE_PASSWORD_ACTION_TYPE = {
  SETTINGS_CHANGE_PASSWORD_FORM_UPLOAD_PENDING:
    'SETTINGS_CHANGE_PASSWORD_ACTION_TYPE.SETTINGS_CHANGE_PASSWORD_FORM_UPLOAD_PENDING',
  SETTINGS_CHANGE_PASSWORD_FORM_UPLOAD_SUCCESS:
    'SETTINGS_CHANGE_PASSWORD_ACTION_TYPE.SETTINGS_CHANGE_PASSWORD_FORM_UPLOAD_SUCCESS',
  SETTINGS_CHANGE_PASSWORD_FORM_UPLOAD_ERROR:
    'SETTINGS_CHANGE_PASSWORD_ACTION_TYPE.SETTINGS_CHANGE_PASSWORD_FORM_UPLOAD_ERROR',
};
