import {
  SETTINGS_CHANGE_PASSWORD_DATA_NAME,
  SETTINGS_CHANGE_PASSWORD_FIELD_NAME,
} from './settings-change-password.type';

export const convertSettingsChangePasswordFormData = (data) => ({
  [SETTINGS_CHANGE_PASSWORD_DATA_NAME.OLD_PASSWORD]:
    data[SETTINGS_CHANGE_PASSWORD_FIELD_NAME.OLD_PASSWORD],
  [SETTINGS_CHANGE_PASSWORD_DATA_NAME.PASSWORD]:
    data[SETTINGS_CHANGE_PASSWORD_FIELD_NAME.PASSWORD],
});
