import { AUTH_FORM_CHANGE_PASSWORD_FIELD_KEY } from './frames/auth-form-change-password';

export const AUTH_CHANGE_PASSWORD_FIELD_NAME = {
  PASSWORD: 'password',
  PASSWORD_REPEAT: 'passwordRepeat',
};

export const AUTH_CHANGE_PASSWORD_FORM_FIELD_NAME = {
  [AUTH_FORM_CHANGE_PASSWORD_FIELD_KEY.PASSWORD]:
    AUTH_CHANGE_PASSWORD_FIELD_NAME.PASSWORD,
  [AUTH_FORM_CHANGE_PASSWORD_FIELD_KEY.PASSWORD_REPEAT]:
    AUTH_CHANGE_PASSWORD_FIELD_NAME.PASSWORD_REPEAT,
};

export const AUTH_CHANGE_PASSWORD_DATA_NAME = {
  CODE: 'code',
  PASSWORD: 'password',
};

export const AUTH_CHANGE_PASSWORD_ACTION_TYPE = {
  AUTH_CHANGE_PASSWORD_FORM_UPLOAD_PENDING:
    'AUTH_CHANGE_PASSWORD_ACTION_TYPE.AUTH_CHANGE_PASSWORD_FORM_UPLOAD_PENDING',
  AUTH_CHANGE_PASSWORD_FORM_UPLOAD_SUCCESS:
    'AUTH_CHANGE_PASSWORD_ACTION_TYPE.AUTH_CHANGE_PASSWORD_FORM_UPLOAD_SUCCESS',
  AUTH_CHANGE_PASSWORD_FORM_UPLOAD_ERROR:
    'AUTH_CHANGE_PASSWORD_ACTION_TYPE.AUTH_CHANGE_PASSWORD_FORM_UPLOAD_ERROR',
};
