export const PURCHASE_PRODUCTS_ACTION_TYPE = {
  PURCHASE_PRODUCTS_DATA_LOAD_PENDING:
    'PURCHASE_PRODUCTS_ACTION_TYPE.PURCHASE_PRODUCTS_DATA_LOAD_PENDING',
  PURCHASE_PRODUCTS_DATA_LOAD_SUCCESS:
    'PURCHASE_PRODUCTS_ACTION_TYPE.PURCHASE_PRODUCTS_DATA_LOAD_SUCCESS',
  PURCHASE_PRODUCTS_DATA_LOAD_ERROR:
    'PURCHASE_PRODUCTS_ACTION_TYPE.PURCHASE_PRODUCTS_DATA_LOAD_ERROR',
};
