export const CREATE_ARTICLE_ACTION_TYPE = {
  CREATE_ARTICLE_UPLOAD_PENDING:
    'CREATE_ARTICLE_ACTION_TYPE.CREATE_ARTICLE_UPLOAD_PENDING',
  CREATE_ARTICLE_UPLOAD_SUCCESS:
    'CREATE_ARTICLE_ACTION_TYPE.CREATE_ARTICLE_UPLOAD_SUCCESS',
  CREATE_ARTICLE_UPLOAD_ERROR:
    'CREATE_ARTICLE_ACTION_TYPE.CREATE_ARTICLE_UPLOAD_ERROR',
};

export const ARTICLE_FIELD_NAME = {
  NAME: 'titleRu',
  MODIFIER: 'modifier',
  IMAGES: 'images',
  IMAGE: 'image',
  CATEGORIES: 'categories',
  CATEGORY: 'textRu',
  ARTICLE: 'articleText',
  RECOMMENDATIONS: 'recommendations',
  TYPE: 'type',
};
