export const MASTER_CLASS_ACTION_TYPE = {
  MASTER_CLASS_UPLOAD_PENDING:
    'MASTER_CLASS_ACTION_TYPE.MASTER_CLASS_UPLOAD_PENDING',
  MASTER_CLASS_UPLOAD_SUCCESS:
    'MASTER_CLASS_ACTION_TYPE.MASTER_CLASS_UPLOAD_SUCCESS',
  MASTER_CLASS_UPLOAD_ERROR:
    'MASTER_CLASS_ACTION_TYPE.MASTER_CLASS_UPLOAD_ERROR',
};
