export const RECENT_COMMENTS_ACTION_TYPE = {
  RESET_COMMENTS_STATE: 'RECENT_COMMENTS_ACTION_TYPE.RESET_COMMENTS_STATE',
  RECENT_COMMENTS_UPLOAD_PENDING: 'RECENT_COMMENTS_ACTION_TYPE.RECENT_COMMENTS_UPLOAD_PENDING',
  RECENT_COMMENTS_UPLOAD_SUCCESS: 'RECENT_COMMENTS_ACTION_TYPE.RECENT_COMMENTS_UPLOAD_SUCCESS',
  RECENT_COMMENTS_UPLOAD_ERROR: 'RECENT_COMMENTS_ACTION_TYPE.RECENT_COMMENTS_UPLOAD_ERROR',
};
