export const FAQ_ACTION_TYPE = {
  FAQ_DATA_UPLOAD_PENDING: 'FAQ_ACTION_TYPE.FAQ_DATA_UPLOAD_PENDING',
  FAQ_DATA_UPLOAD_SUCCESS: 'FAQ_ACTION_TYPE.FAQ_DATA_UPLOAD_SUCCESS',
  FAQ_DATA_UPLOAD_ERROR: 'FAQ_ACTION_TYPE.FAQ_DATA_UPLOAD_ERROR',
};
