export const PAYMENT_METHOD_STORE_NAME = 'PAYMENT_METHOD';
export const PAYMENT_METHOD_LOCAL_STORAGE_KEY = 'PAYMENT_METHOD';

export enum PAYMENT_METHOD_ACTION_TYPE {
  SET_METHOD = 'PAYMENT_METHOD_ACTION_TYPE.SET_METHOD',
}
