export const PATTERNS_PRODUCT_ACTION_TYPE = {
  PATTERNS_PRODUCT_UPLOAD_PENDING:
    'PATTERNS_PRODUCT_ACTION_TYPE.PATTERNS_PRODUCT_UPLOAD_PENDING',
  PATTERNS_PRODUCT_UPLOAD_SUCCESS:
    'PATTERNS_PRODUCT_ACTION_TYPE.PATTERNS_PRODUCT_UPLOAD_SUCCESS',
  PATTERNS_PRODUCT_UPLOAD_ERROR:
    'PATTERNS_PRODUCT_ACTION_TYPE.PATTERNS_PRODUCT_UPLOAD_ERROR',
};
