export const ALL_PRODUCTS_ACTION_TYPE = {
  RESET_PRODUCTS_STATE: 'ALL_PRODUCTS_ACTION_TYPE.RESET_PRODUCTS_STATE',
  ALL_PRODUCTS_UPLOAD_PENDING:
    'ALL_PRODUCTS_ACTION_TYPE.ALL_PRODUCTS_UPLOAD_PENDING',
  ALL_PRODUCTS_UPLOAD_SUCCESS:
    'ALL_PRODUCTS_ACTION_TYPE.ALL_PRODUCTS_UPLOAD_SUCCESS',
  ALL_PRODUCTS_UPLOAD_ERROR:
    'ALL_PRODUCTS_ACTION_TYPE.ALL_PRODUCTS_UPLOAD_ERROR',

  CATEGORIES_UPLOAD_PENDING:
    'ALL_PRODUCTS_ACTION_TYPE.CATEGORIES_UPLOAD_PENDING',
  CATEGORIES_UPLOAD_SUCCESS:
    'ALL_PRODUCTS_ACTION_TYPE.CATEGORIES_UPLOAD_SUCCESS',
  CATEGORIES_UPLOAD_ERROR: 'ALL_PRODUCTS_ACTION_TYPE.CATEGORIES_UPLOAD_ERROR',

  DISABLE_PRODUCT_PENDING: 'ALL_PRODUCTS_ACTION_TYPE.DISABLE_PRODUCT_PENDING',
  DISABLE_PRODUCT_SUCCESS: 'ALL_PRODUCTS_ACTION_TYPE.DISABLE_PRODUCT_SUCCESS',
  DISABLE_PRODUCT_ERROR: 'ALL_PRODUCTS_ACTION_TYPE.DISABLE_PRODUCT_ERROR',

  ALL_PRODUCTS_PAGINATION_PENDING:
    'ALL_PRODUCTS_ACTION_TYPE.ALL_PRODUCTS_PAGINATION_PENDING',
  ALL_PRODUCTS_PAGINATION_SUCCESS:
    'ALL_PRODUCTS_ACTION_TYPE.ALL_PRODUCTS_PAGINATION_SUCCESS',
  ALL_PRODUCTS_PAGINATION_ERROR:
    'ALL_PRODUCTS_ACTION_TYPE.ALL_PRODUCTS_PAGINATION_ERROR',
};
