export const FORMALIZATION_ORDERING_FIELD_KEY = {
  FULL_NAME: 'FULL_NAME',
  CURRENT_CITY: 'CURRENT_CITY',
  CONVENIENT_DELIVERY_METHOD: 'CONVENIENT_DELIVERY_METHOD',
  CONVENIENT_PAYMENT_METHOD: 'CONVENIENT_PAYMENT_METHOD',
  CONTACT_PHONE_NUMBER: 'CONTACT_PHONE_NUMBER',
  ORDER_NOTE: 'ORDER_NOTE',
};
