export const SEARCH_BUTTON_ACTION_TYPE = {
  MASTER_CLASSES_UPLOAD_PENDING:
    'SEARCH_BUTTON_ACTION_TYPE.MASTER_CLASSES_UPLOAD_PENDING',
  MASTER_CLASSES_UPLOAD_SUCCESS:
    'SEARCH_BUTTON_ACTION_TYPE.MASTER_CLASSES_UPLOAD_SUCCESS',
  MASTER_CLASSES_UPLOAD_ERROR:
    'SEARCH_BUTTON_ACTION_TYPE.MASTER_CLASSES_UPLOAD_ERROR',
  PATTERNS_UPLOAD_PENDING: 'SEARCH_BUTTON_ACTION_TYPE.PATTERNS_UPLOAD_PENDING',
  PATTERNS_UPLOAD_SUCCESS: 'SEARCH_BUTTON_ACTION_TYPE.PATTERNS_UPLOAD_SUCCESS',
  PATTERNS_UPLOAD_ERROR: 'SEARCH_BUTTON_ACTION_TYPE.PATTERNS_UPLOAD_ERROR',
  SEWING_GOODS_UPLOAD_PENDING:
    'SEARCH_BUTTON_ACTION_TYPE.SEWING_GOODS_UPLOAD_PENDING',
  SEWING_GOODS_UPLOAD_SUCCESS:
    'SEARCH_BUTTON_ACTION_TYPE.SEWING_GOODS_UPLOAD_SUCCESS',
  SEWING_GOODS_UPLOAD_ERROR:
    'SEARCH_BUTTON_ACTION_TYPE.SEWING_GOODS_UPLOAD_ERROR',
  ARTICLES_UPLOAD_PENDING: 'SEARCH_BUTTON_ACTION_TYPE.ARTICLES_UPLOAD_PENDING',
  ARTICLES_UPLOAD_SUCCESS: 'SEARCH_BUTTON_ACTION_TYPE.ARTICLES_UPLOAD_SUCCESS',
  ARTICLES_UPLOAD_ERROR: 'SEARCH_BUTTON_ACTION_TYPE.ARTICLES_UPLOAD_ERROR',
};
