export const SEARCH_BUTTON_ACTION_TYPE = {
  RESET_PRODUCTS_STATE: 'SEARCH_BUTTON_ACTION_TYPE.RESET_PRODUCTS_STATE',
  PRODUCTS_UPLOAD_PENDING: 'SEARCH_BUTTON_ACTION_TYPE.PRODUCTS_UPLOAD_PENDING',
  PRODUCTS_UPLOAD_SUCCESS: 'SEARCH_BUTTON_ACTION_TYPE.PRODUCTS_UPLOAD_SUCCESS',
  PRODUCTS_UPLOAD_ERROR: 'SEARCH_BUTTON_ACTION_TYPE.PRODUCTS_UPLOAD_ERROR',
};
