export const ARTICLE_PAGE_ACTION_TYPE = {
  ARTICLE_PAGE_UPLOAD_PENDING: 'ARTICLE_PAGE_ACTION_TYPE.ARTICLE_PAGE_UPLOAD_PENDING',
  ARTICLE_PAGE_UPLOAD_SUCCESS: 'ARTICLE_PAGE_ACTION_TYPE.ARTICLE_PAGE_UPLOAD_SUCCESS',
  ARTICLE_PAGE_UPLOAD_ERROR: 'ARTICLE_PAGE_ACTION_TYPE.ARTICLE_PAGE_UPLOAD_ERROR',
};
