import { PUBLICATION_FORM_FILTER_FIELD_KEY } from './frames/publication-form-filter';

export const PUBLICATION_FILTER_FIELD_NAME = {
  CATEGORY: 'category',
  TAGS: 'tags',
  FIND_PUBLICATION: 'findPublication',
};

export const PUBLICATION_FORM_FILTER_FIELD_NAME = {
  [PUBLICATION_FORM_FILTER_FIELD_KEY.CATEGORY]:
    PUBLICATION_FILTER_FIELD_NAME.CATEGORY,
  [PUBLICATION_FORM_FILTER_FIELD_KEY.TAGS]: PUBLICATION_FILTER_FIELD_NAME.TAGS,
  [PUBLICATION_FORM_FILTER_FIELD_KEY.FIND_PUBLICATION]:
    PUBLICATION_FILTER_FIELD_NAME.FIND_PUBLICATION,
};
