export const PATTERNS_ACTION_TYPE = {
  RESET_PRODUCTS_STATE: 'PATTERNS_ACTION_TYPE.RESET_PRODUCTS_STATE',
  PATTERNS_UPLOAD_PENDING: 'PATTERNS_ACTION_TYPE.PATTERNS_UPLOAD_PENDING',
  PATTERNS_UPLOAD_SUCCESS: 'PATTERNS_ACTION_TYPE.PATTERNS_UPLOAD_SUCCESS',
  PATTERNS_UPLOAD_ERROR: 'PATTERNS_ACTION_TYPE.PATTERNS_UPLOAD_ERROR',
  CATEGORIES_UPLOAD_PENDING: 'PATTERNS_ACTION_TYPE.CATEGORIES_UPLOAD_PENDING',
  CATEGORIES_UPLOAD_SUCCESS: 'PATTERNS_ACTION_TYPE.CATEGORIES_UPLOAD_SUCCESS',
  CATEGORIES_UPLOAD_ERROR: 'PATTERNS_ACTION_TYPE.CATEGORIES_UPLOAD_ERROR',
};
