export const PATTERNS_ACTION_TYPE = {
  PATTERNS_UPLOAD_PENDING: 'PATTERNS_ACTION_TYPE.PATTERNS_UPLOAD_PENDING',
  PATTERNS_UPLOAD_SUCCESS: 'PATTERNS_ACTION_TYPE.PATTERNS_UPLOAD_SUCCESS',
  PATTERNS_PAGINATION_SUCCESS:
    'PATTERNS_ACTION_TYPE.PATTERNS_PAGINATION_SUCCESS',
  PATTERNS_UPLOAD_ERROR: 'PATTERNS_ACTION_TYPE.PATTERNS_UPLOAD_ERROR',
  PATTERNS_UPDATE_PENDING: 'PATTERNS_ACTION_TYPE.PATTERNS_UPDATE_PENDING',
  PATTERNS_UPDATE_SUCCESS: 'PATTERNS_ACTION_TYPE.PATTERNS_UPDATE_SUCCESS',
  PATTERNS_UPDATE_ERROR: 'PATTERNS_ACTION_TYPE.PATTERNS_UPDATE_ERROR',
};
