export const PATTERNS_FIELD_NAME = {
  CATEGORY: 'category',
  TAGS: 'tags',
  FIND_INPUT: 'find-input-patterns',
};

export const PATTERNS_ACTION_TYPE = {
  PATTERNS_UPLOAD_PENDING: 'PATTERNS_ACTION_TYPE.PATTERNS_UPLOAD_PENDING',
  PATTERNS_UPLOAD_SUCCESS: 'PATTERNS_ACTION_TYPE.PATTERNS_UPLOAD_SUCCESS',
  PATTERNS_UPLOAD_ERROR: 'PATTERNS_ACTION_TYPE.PATTERNS_UPLOAD_ERROR',
};
