export const AUTH_VERIFICATE_EMAIL_CONFIRM_ACTION_TYPE = {
  AUTH_VERIFICATE_EMAIL_CONFIRM_UPLOAD_PENDING:
    'AUTH_VERIFICATE_EMAIL_CONFIRM_ACTION_TYPE.AUTH_VERIFICATE_EMAIL_CONFIRM_UPLOAD_PENDING',
  AUTH_VERIFICATE_EMAIL_CONFIRM_UPLOAD_SUCCESS:
    'AUTH_VERIFICATE_EMAIL_CONFIRM_ACTION_TYPE.AUTH_VERIFICATE_EMAIL_CONFIRM_UPLOAD_SUCCESS',
  AUTH_VERIFICATE_EMAIL_CONFIRM_UPLOAD_ERROR:
    'AUTH_VERIFICATE_EMAIL_CONFIRM_ACTION_TYPE.AUTH_VERIFICATE_EMAIL_CONFIRM_UPLOAD_ERROR',
};
