export const USER_ORDERS_ACTION_TYPE = {
  USER_ORDERS_UPLOAD_PENDING: 'USER_ORDERS_ACTION_TYPE.USER_ORDERS_UPLOAD_PENDING',
  USER_ORDERS_UPLOAD_SUCCESS: 'USER_ORDERS_ACTION_TYPE.USER_ORDERS_UPLOAD_SUCCESS',
  USER_ORDERS_UPLOAD_ERROR: 'USER_ORDERS_ACTION_TYPE.USER_ORDERS_UPLOAD_ERROR',
};
