export const TERMS_OF_USE_ACTION_TYPE = {
  TERMS_OF_USE_DATA_UPLOAD_PENDING:
    'TERMS_OF_USE_ACTION_TYPE.TERMS_OF_USE_DATA_UPLOAD_PENDING',
  TERMS_OF_USE_DATA_UPLOAD_SUCCESS:
    'TERMS_OF_USE_ACTION_TYPE.TERMS_OF_USE_DATA_UPLOAD_SUCCESS',
  TERMS_OF_USE_DATA_UPLOAD_ERROR:
    'TERMS_OF_USE_ACTION_TYPE.TERMS_OF_USE_DATA_UPLOAD_ERROR',
};
