export const PRIVACY_POLICY_ACTION_TYPE = {
  PRIVACY_POLICY_DATA_SAVE_PENDING:
    'PRIVACY_POLICY_ACTION_TYPE.PRIVACY_POLICY_DATA_SAVE_PENDING',
  PRIVACY_POLICY_DATA_SAVE_SUCCESS:
    'PRIVACY_POLICY_ACTION_TYPE.PRIVACY_POLICY_DATA_SAVE_SUCCESS',
  PRIVACY_POLICY_DATA_SAVE_ERROR:
    'PRIVACY_POLICY_ACTION_TYPE.PRIVACY_POLICY_DATA_SAVE_ERROR',

  PRIVACY_POLICY_DATA_UPLOAD_PENDING:
    'PRIVACY_POLICY_ACTION_TYPE.PRIVACY_POLICY_DATA_UPLOAD_PENDING',
  PRIVACY_POLICY_DATA_UPLOAD_SUCCESS:
    'PRIVACY_POLICY_ACTION_TYPE.PRIVACY_POLICY_DATA_UPLOAD_SUCCESS',
  PRIVACY_POLICY_DATA_UPLOAD_ERROR:
    'PRIVACY_POLICY_ACTION_TYPE.PRIVACY_POLICY_DATA_UPLOAD_ERROR',
};
