export const DELIVERY_PRICE_PAGE_ACTION_TYPE = {
  DELIVERY_PRICE_PAGE_DATA_UPLOAD_PENDING:
    'DELIVERY_PRICE_PAGE_ACTION_TYPE.DELIVERY_PRICE_PAGE_DATA_UPLOAD_PENDING',
  DELIVERY_PRICE_PAGE_DATA_UPLOAD_SUCCESS:
    'DELIVERY_PRICE_PAGE_ACTION_TYPE.DELIVERY_PRICE_PAGE_DATA_UPLOAD_SUCCESS',
  DELIVERY_PRICE_PAGE_DATA_UPLOAD_ERROR:
    'DELIVERY_PRICE_PAGE_ACTION_TYPE.DELIVERY_PRICE_PAGE_DATA_UPLOAD_ERROR',
};
