export const ABOUT_ACCOUNT_ACTION_TYPE = {
  USER_LOAD_DATA_PENDING: 'ABOUT_ACCOUNT_ACTION_TYPE.USER_LOAD_DATA_PENDING',
  USER_LOAD_DATA_SUCCESS: 'ABOUT_ACCOUNT_ACTION_TYPE.USER_LOAD_DATA_SUCCESS',
  USER_LOAD_DATA_ERROR: 'ABOUT_ACCOUNT_ACTION_TYPE.USER_LOAD_DATA_ERROR',
  USER_DELIVERY_INFO_PENDING: 'ABOUT_ACCOUNT_ACTION_TYPE.USER_DELIVERY_INFO_PENDING',
  USER_DELIVERY_INFO_SUCCESS: 'ABOUT_ACCOUNT_ACTION_TYPE.USER_DELIVERY_INFO_SUCCESS',
  USER_DELIVERY_INFO_ERROR: 'ABOUT_ACCOUNT_ACTION_TYPE.USER_DELIVERY_INFO_ERROR',
  LIKES_PENDING: 'ABOUT_ACCOUNT_ACTION_TYPE.LIKES_PENDING',
  LIKES_SUCCESS: 'ABOUT_ACCOUNT_ACTION_TYPE.LIKES_SUCCESS',
  LIKES_ERROR: 'ABOUT_ACCOUNT_ACTION_TYPE.LIKES_ERROR',
};
