export const ABOUT_ACCOUNT_ACTION_TYPE = {
  ABOUT_ACCOUNT_UPLOAD_PENDING: 'ABOUT_ACCOUNT_ACTION_TYPE.ABOUT_ACCOUNT_UPLOAD_PENDING',
  ABOUT_ACCOUNT_UPLOAD_SUCCESS: 'ABOUT_ACCOUNT_ACTION_TYPE.ABOUT_ACCOUNT_UPLOAD_SUCCESS',
  ABOUT_ACCOUNT_UPLOAD_ERROR: 'ABOUT_ACCOUNT_ACTION_TYPE.ABOUT_ACCOUNT_UPLOAD_ERROR',
};
