export const ABOUT_ACCOUNT_ACTION_TYPE = {
  USER_LOAD_DATA_PENDING: 'ABOUT_ACCOUNT_ACTION_TYPE.USER_LOAD_DATA_PENDING',
  USER_LOAD_DATA_SUCCESS: 'ABOUT_ACCOUNT_ACTION_TYPE.USER_LOAD_DATA_SUCCESS',
  USER_LOAD_DATA_ERROR: 'ABOUT_ACCOUNT_ACTION_TYPE.USER_LOAD_DATA_ERROR',
  PURCHASES_PENDING: 'ABOUT_ACCOUNT_ACTION_TYPE.PURCHASES_PENDING',
  PURCHASES_SUCCESS: 'ABOUT_ACCOUNT_ACTION_TYPE.PURCHASES_SUCCESS',
  PURCHASES_ERROR: 'ABOUT_ACCOUNT_ACTION_TYPE.PURCHASES_ERROR',
  LIKES_PENDING: 'ABOUT_ACCOUNT_ACTION_TYPE.LIKES_PENDING',
  LIKES_SUCCESS: 'ABOUT_ACCOUNT_ACTION_TYPE.LIKES_SUCCESS',
  LIKES_ERROR: 'ABOUT_ACCOUNT_ACTION_TYPE.LIKES_ERROR',
  COMMENTS_PENDING: 'ABOUT_ACCOUNT_ACTION_TYPE.COMMENTS_PENDING',
  COMMENTS_SUCCESS: 'ABOUT_ACCOUNT_ACTION_TYPE.COMMENTS_SUCCESS',
  COMMENTS_ERROR: 'ABOUT_ACCOUNT_ACTION_TYPE.COMMENTS_ERROR',
};
