export const LOGIN_FIELD_NAME = {
  LOGIN: 'login',
  PASSWORD: 'password',
};
export const LOGIN_ACTION_TYPE = {
  LOGIN_FORM_UPLOAD_PENDING: 'LOGIN_ACTION_TYPE.AUTH_FORM_UPLOAD_PENDING',
  LOGIN_FORM_UPLOAD_SUCCESS: 'LOGIN_ACTION_TYPE.AUTH_FORM_UPLOAD_SUCCESS',
  LOGIN_FORM_UPLOAD_ERROR: 'LOGIN_ACTION_TYPE.AUTH_FORM_UPLOAD_ERROR',
};
