export const FORMALIZATION_ORDERING_FIELD_NAME = {
  FULL_NAME: 'fullName',
  CURRENT_CITY: 'currentCity',
  CONVENIENT_DELIVERY_METHOD: 'convenientDeliveryMethod',
  CONVENIENT_PAYMENT_METHOD: 'convenientPaymentMethod',
  CONTACT_PHONE_NUMBER: 'contactPhoneNumber',
  ORDER_NOTE: 'OrderNote',
  PROMO_CODE: 'promoCode',
};

export const BASKET_ACTION_TYPE = {
  BASKET_UPLOAD_PENDING: 'BASKET_ACTION_TYPE.BASKET_UPLOAD_PENDING',
  BASKET_UPLOAD_SUCCESS: 'BASKET_ACTION_TYPE.BASKET_UPLOAD_SUCCESS',
  BASKET_UPLOAD_ERROR: 'BASKET_ACTION_TYPE.BASKET_UPLOAD_ERROR',
};
