import { FORMALIZATION_ORDERING_FIELD_KEY } from './frames/formalization-ordering/formalization-ordering.type';
import { PROMO_CODE_FIELD_KEY } from './frames/promo-code/promo-code.type';

export const FORMALIZATION_ORDERING_FIELD_NAME = {
  FULL_NAME: 'fullName',
  CURRENT_CITY: 'currentCity',
  CONVENIENT_DELIVERY_METHOD: 'convenientDeliveryMethod',
  CONVENIENT_PAYMENT_METHOD: 'convenientPaymentMethod',
  CONTACT_PHONE_NUMBER: 'contactPhoneNumber',
  ORDER_NOTE: 'OrderNote',
  PROMO_CODE: 'promocode',
};

export const FORMALIZATION_ORDERING_FORM_FIELD_NAME = {
  [FORMALIZATION_ORDERING_FIELD_KEY.FULL_NAME]:
    FORMALIZATION_ORDERING_FIELD_NAME.FULL_NAME,
  [FORMALIZATION_ORDERING_FIELD_KEY.CONTACT_PHONE_NUMBER]:
    FORMALIZATION_ORDERING_FIELD_NAME.CONTACT_PHONE_NUMBER,
  [FORMALIZATION_ORDERING_FIELD_KEY.CONVENIENT_DELIVERY_METHOD]:
    FORMALIZATION_ORDERING_FIELD_NAME.CONVENIENT_DELIVERY_METHOD,
  [FORMALIZATION_ORDERING_FIELD_KEY.CURRENT_CITY]:
    FORMALIZATION_ORDERING_FIELD_NAME.CURRENT_CITY,
  [FORMALIZATION_ORDERING_FIELD_KEY.ORDER_NOTE]:
    FORMALIZATION_ORDERING_FIELD_NAME.ORDER_NOTE,
  [PROMO_CODE_FIELD_KEY.PROMO_CODE]:
    FORMALIZATION_ORDERING_FIELD_NAME.PROMO_CODE,
};

export const BASKET_ACTION_TYPE = {
  BASKET_UPLOAD_PENDING: 'BASKET_ACTION_TYPE.BASKET_UPLOAD_PENDING',
  BASKET_UPLOAD_SUCCESS: 'BASKET_ACTION_TYPE.BASKET_UPLOAD_SUCCESS',
  BASKET_UPLOAD_ERROR: 'BASKET_ACTION_TYPE.BASKET_UPLOAD_ERROR',

  BASKET_LOAD_USER_INFO_DATA_PENDING:
    'BASKET_ACTION_TYPE.BASKET_LOAD_USER_INFO_DATA_PENDING',
  BASKET_LOAD_USER_INFO_DATA_SUCCESS:
    'BASKET_ACTION_TYPE.BASKET_LOAD_USER_INFO_DATA_SUCCESS',
  BASKET_LOAD_USER_INFO_DATA_ERROR:
    'BASKET_ACTION_TYPE.BASKET_LOAD_USER_INFO_DATA_ERROR',

  CHECK_PROMO_CODE_PENDING: 'BASKET_ACTION_TYPE.CHECK_PROMO_CODE_PENDING',
  CHECK_PROMO_CODE_SUCCESS: 'BASKET_ACTION_TYPE.CHECK_PROMO_CODE_SUCCESS',
  CHECK_PROMO_CODE_ERROR: 'BASKET_ACTION_TYPE.CHECK_PROMO_CODE_ERROR',
};

export const BASKET_DATA_NAME = {
  FULLNAME: 'fullname',
  PHONE: 'phone',
  LOCATION: 'location',
  DELIVERY_TYPE: 'deliveryType',
  DISCOUNT: 'discount',
  PROMO_CODE: 'text',
};

export const BASKET_DATA_KEY = {
  FULLNAME: 'FULLNAME',
  PHONE: 'PHONE',
  LOCATION: 'LOCATION',
  DELIVERY_TYPE: 'DELIVERY_TYPE',
  DISCOUNT: 'DISCOUNT',
};
