export const MY_LIKES_ACTION_TYPE = {
  MY_LIKES_UPLOAD_PENDING: 'MY_LIKES_ACTION_TYPE.MY_LIKES_UPLOAD_PENDING',
  MY_LIKES_UPLOAD_SUCCESS: 'MY_LIKES_ACTION_TYPE.MY_LIKES_UPLOAD_SUCCESS',
  MY_LIKES_UPLOAD_ERROR: 'MY_LIKES_ACTION_TYPE.MY_LIKES_UPLOAD_ERROR',
};
