export const CREATE_PRODUCT_ACTION_TYPE = {
  CREATE_PRODUCT_UPLOAD_PENDING: 'CREATE_PRODUCT_ACTION_TYPE.CREATE_PRODUCT_UPLOAD_PENDING',
  CREATE_PRODUCT_UPLOAD_SUCCESS: 'CREATE_PRODUCT_ACTION_TYPE.CREATE_PRODUCT_UPLOAD_SUCCESS',
  CREATE_PRODUCT_UPLOAD_ERROR: 'CREATE_PRODUCT_ACTION_TYPE.CREATE_PRODUCT_UPLOAD_ERROR',
};
