export const CREATE_PRODUCT_ACTION_TYPE = {
  CREATE_PRODUCT_UPLOAD_PENDING:
    'CREATE_PRODUCT_ACTION_TYPE.CREATE_PRODUCT_UPLOAD_PENDING',
  CREATE_PRODUCT_UPLOAD_SUCCESS:
    'CREATE_PRODUCT_ACTION_TYPE.CREATE_PRODUCT_UPLOAD_SUCCESS',
  CREATE_PRODUCT_UPLOAD_ERROR:
    'CREATE_PRODUCT_ACTION_TYPE.CREATE_PRODUCT_UPLOAD_ERROR',
};

export const PRODUCT_FIELD_NAME = {
  NAME: 'titleRu',
  TYPE: 'type',
  MODIFIER: 'modifier',
  DESCRIPTION: 'descriptionRu',
  DISCOUNT: 'discount',
  CATEGORIES: 'categories',
  CATEGORY_NAME: 'category',
  IMAGES: 'imageUrls',

  MATERIAL: 'material',
  COMPLEXITY: 'complexity',

  ELECTRONIC_PATTERN_PRICE: 'price',
  ELECTRONIC_PATTERN_FILE: 'file',

  COUNT: 'count',

  SIZES: 'sizes',
  SIZE_NAME: 'size',
  SIZE_PRICE: 'price',

  COLORS: 'colors',
  COLOR_NAME: 'color',
  COLOR_PRICE: 'price',

  PROGRAMS: 'programs',
  PROGRAM_NAME: 'name',
  PROGRAM_PRICE: 'price',
};
