export const CREATE_PRINT_PATTERN_ACTION_TYPE = {
  CREATE_PRINT_PATTERN_UPLOAD_PENDING:
    'CREATE_PRINT_PATTERN_ACTION_TYPE.CREATE_PRINT_PATTERN_UPLOAD_PENDING',
  CREATE_PRINT_PATTERN_UPLOAD_SUCCESS:
    'CREATE_PRINT_PATTERN_ACTION_TYPE.CREATE_PRINT_PATTERN_UPLOAD_SUCCESS',
  CREATE_PRINT_PATTERN_UPLOAD_ERROR:
    'CREATE_PRINT_PATTERN_ACTION_TYPE.CREATE_PRINT_PATTERN_UPLOAD_ERROR',
};

export const PRINT_PATTERN_FIELD_NAME = {
  TYPE: 'type',
  NAME: 'titleRu',
  DESCRIPTION: 'descriptionRu',
  MODIFIER: 'modifierRu',
  MATERIAL: 'materialRu',
  IMAGES: 'images',
  IMAGE: 'image',
  COMPLEXITY: 'complexity',
  RECOMMENDATIONS: 'recommendation',
  CATEGORIES: 'categories',
  OPTIONS: 'options',
  OPTION_SIZE: 'size',
  OPTION_PRICE: 'price',
  OPTION_DISCOUNT: 'discount',
};
