export const CREATE_PRINT_PATTERN_ACTION_TYPE = {
  CREATE_PRINT_PATTERN_UPLOAD_PENDING:
    'CREATE_PRINT_PATTERN_ACTION_TYPE.CREATE_PRINT_PATTERN_UPLOAD_PENDING',
  CREATE_PRINT_PATTERN_UPLOAD_SUCCESS:
    'CREATE_PRINT_PATTERN_ACTION_TYPE.CREATE_PRINT_PATTERN_UPLOAD_SUCCESS',
  CREATE_PRINT_PATTERN_UPLOAD_ERROR:
    'CREATE_PRINT_PATTERN_ACTION_TYPE.CREATE_PRINT_PATTERN_UPLOAD_ERROR',
};

export const PRINT_PATTERN_FIELD_NAME = {
  NAME: 'titleRu',
  DESCRIPTION: 'descriptionRu',
  TYPE: 'type',
  MODIFIER: 'modifier',
  DISCOUNT: 'discount',
  IMAGES: 'images',
  IMAGE: 'image',

  MATERIAL: 'materialRu',
  COMPLEXITY: 'complexity',

  CATEGORIES: 'categories',
  CATEGORY: 'textRu',

  RECOMMENDATIONS: 'recommendation',

  SIZES: 'sizes',
  SIZE_NAME: 'size',
  SIZE_PRICE: 'price',
};
