export const EMAIL_CONFIRMED_ACTION_TYPE = {
  CHECK_EMAIL_CONFIRMED_PENDING:
    'EMAIL_CONFIRMED_ACTION_TYPE.CHECK_EMAIL_CONFIRMED_PENDING',
  CHECK_EMAIL_CONFIRMED_SUCCESS:
    'EMAIL_CONFIRMED_ACTION_TYPE.CHECK_EMAIL_CONFIRMED_SUCCESS',
  CHECK_EMAIL_CONFIRMED_ERROR:
    'EMAIL_CONFIRMED_ACTION_TYPE.CHECK_EMAIL_CONFIRMED_ERROR',
};
