import { SUBSCRIBE_FORM_FIELD_KEY } from './frames/email-subscribe';

export const SUBSCRIBE_FIELD_NAME = {
  EMAIL: 'email',
};

export const SUBSCRIBE_FORM_FIELD_NAME = {
  [SUBSCRIBE_FORM_FIELD_KEY.EMAIL]: SUBSCRIBE_FIELD_NAME.EMAIL,
};

export const SUBSCRIBE_DATA_NAME = {
  EMAIL: 'email',
};

export const SUBSCRIBE_ACTION_TYPE = {
  SUBSCRIBE_FORM_UPLOAD_PENDING:
    'SUBSCRIBE_ACTION_TYPE.SUBSCRIBE_FORM_UPLOAD_PENDING',
  SUBSCRIBE_FORM_UPLOAD_SUCCESS:
    'SUBSCRIBE_ACTION_TYPE.SUBSCRIBE_FORM_UPLOAD_SUCCESS',
  SUBSCRIBE_FORM_UPLOAD_ERROR:
    'SUBSCRIBE_ACTION_TYPE.SUBSCRIBE_FORM_UPLOAD_ERROR',
};
