export const ABOUT_ORDER_FIELD_NAME = {
  ID: 'id',
  CITY: 'city',
  EMAIL: 'email',
  FULL_NAME: 'fullName',
  ORDER_NUMBER: 'orderNumber',
  PHONE_NUMBER: 'phoneNumber',
  ORDER_STATUS: 'orderStatus',
  PRICE: 'price',
  PROMO_CODE: 'promoCode',
  COMMENT: 'comment',
  PROMO_CODE_DISCOUNT: 'promoCodeDiscount',
  DELIVERY_METHOD: 'typeOfDelivery',
  // PAYMENT_METHOD: 'paymentMethod',
};

export const ORDER_NUMBER_ACTION_TYPE = {
  ORDER_NUMBER_UPLOAD_PENDING:
    'ORDER_NUMBER_ACTION_TYPE.ORDER_NUMBER_UPLOAD_PENDING',
  ORDER_NUMBER_UPLOAD_SUCCESS:
    'ORDER_NUMBER_ACTION_TYPE.ORDER_NUMBER_UPLOAD_SUCCESS',
  ORDER_NUMBER_UPLOAD_ERROR:
    'ORDER_NUMBER_ACTION_TYPE.ORDER_NUMBER_UPLOAD_ERROR',

  ORDER_NUMBER_UPDATE_PENDING:
    'ORDER_NUMBER_ACTION_TYPE.ORDER_NUMBER_UPDATE_PENDING',
  ORDER_NUMBER_UPDATE_SUCCESS:
    'ORDER_NUMBER_ACTION_TYPE.ORDER_NUMBER_UPDATE_SUCCESS',
  ORDER_NUMBER_UPDATE_ERROR:
    'ORDER_NUMBER_ACTION_TYPE.ORDER_NUMBER_UPLOAD_ERROR',

  ORDER_PRODUCT_CHANGE: 'ORDER_NUMBER_ACTION_TYPE.ORDER_PRODUCT_CHANGE',
  ORDER_PRODUCT_DELETE: 'ORDER_NUMBER_ACTION_TYPE.ORDER_PRODUCT_DELETE',
  ORDER_PRODUCT_INIT: 'ORDER_NUMBER_ACTION_TYPE.ORDER_PRODUCT_INIT',
};
