export const ABOUT_ORDER_FIELD_NAME = {
  FULL_NAME: 'fullName',
  CURRENT_CITY: 'currentCity',
  CONVENIENT_DELIVERY_METHOD: 'convenientDeliveryMethod',
  CONVENIENT_PAYMENT_METHOD: 'convenientPaymentMethod',
  CONTACT_PHONE_NUMBER: 'contactPhoneNumber',
  ORDER_NOTE: 'orderNote',
  ORDER_STATUS: 'orderStatus',
  PROMO_CODE: 'promoCode',
};

export const ORDER_NUMBER_ACTION_TYPE = {
  ORDER_NUMBER_UPLOAD_PENDING:
    'ORDER_NUMBER_ACTION_TYPE.ORDER_NUMBER_UPLOAD_PENDING',
  ORDER_NUMBER_UPLOAD_SUCCESS:
    'ORDER_NUMBER_ACTION_TYPE.ORDER_NUMBER_UPLOAD_SUCCESS',
  ORDER_NUMBER_UPLOAD_ERROR:
    'ORDER_NUMBER_ACTION_TYPE.ORDER_NUMBER_UPLOAD_ERROR',
};
