export const CREATE_NOTIFICATION_ACTION_TYPE = {
  CREATE_NOTIFICATION_UPLOAD_PENDING:
    'CREATE_NOTIFICATION_ACTION_TYPE.CREATE_NOTIFICATION_UPLOAD_PENDING',
  CREATE_NOTIFICATION_UPLOAD_SUCCESS:
    'CREATE_NOTIFICATION_ACTION_TYPE.CREATE_NOTIFICATION_UPLOAD_SUCCESS',
  CREATE_NOTIFICATION_UPLOAD_ERROR:
    'CREATE_NOTIFICATION_ACTION_TYPE.CREATE_NOTIFICATION_UPLOAD_ERROR',
};

export const CREATE_NOTIFICATION_FIELD_NAME = {
  SUBJECT: 'subject',
  NOTIFICATION: 'notification',
};

export const CREATE_NOTIFICATION_DATA_NAME = {
  SUBJECT: 'subject',
  HTML: 'html',
};
