export const DELIVERY_PAYMENT_ACTION_TYPE = {
  DATA_GET_PENDING: 'DELIVERY_PAYMENT_ACTION_TYPE.DATA_GET_PENDING',
  DATA_GET_SUCCESS: 'DELIVERY_PAYMENT_ACTION_TYPE.DATA_GET_SUCCESS',
  DATA_GET_ERROR: 'DELIVERY_PAYMENT_ACTION_TYPE.DATA_GET_ERROR',

  DATA_SAVE_PENDING: 'DELIVERY_PAYMENT_ACTION_TYPE.DATA_SAVE_PENDING',
  DATA_SAVE_SUCCESS: 'DELIVERY_PAYMENT_ACTION_TYPE.DATA_SAVE_SUCCESS',
  DATA_SAVE_ERROR: 'DELIVERY_PAYMENT_ACTION_TYPE.DATA_SAVE_ERROR',
};
