export const LIKES_ACTION_TYPE = {
  RESET_PRODUCTS_STATE: 'LIKES_ACTION_TYPE.RESET_PRODUCTS_STATE',
  GET_LIKES_PENDING: 'LIKES_ACTION_TYPE.GET_LIKES_PENDING',
  GET_LIKES_SUCCESS: 'LIKES_ACTION_TYPE.GET_LIKES_SUCCESS',
  GET_LIKES_ERROR: 'LIKES_ACTION_TYPE.GET_LIKES_ERROR',

  GET_CATEGORIES_PENDING: 'LIKES_ACTION_TYPE.GET_CATEGORIES_PENDING',
  GET_CATEGORIES_SUCCESS: 'LIKES_ACTION_TYPE.GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_ERROR: 'LIKES_ACTION_TYPE.GET_CATEGORIES_ERROR',

  PAGINATION_LIKES_PENDING: 'LIKES_ACTION_TYPE.PAGINATION_LIKES_PENDING',
  PAGINATION_LIKES_SUCCESS: 'LIKES_ACTION_TYPE.PAGINATION_LIKES_SUCCESS',
  PAGINATION_LIKES_ERROR: 'LIKES_ACTION_TYPE.PAGINATION_LIKES_ERROR',
};
