export const LIKES_ACTION_TYPE = {
  RESET_PRODUCTS_STATE: 'LIKES_ACTION_TYPE.RESET_PRODUCTS_STATE',
  LIKES_UPLOAD_PENDING: 'LIKES_ACTION_TYPE.LIKES_UPLOAD_PENDING',
  LIKES_UPLOAD_SUCCESS: 'LIKES_ACTION_TYPE.LIKES_UPLOAD_SUCCESS',
  LIKES_UPLOAD_ERROR: 'LIKES_ACTION_TYPE.LIKES_UPLOAD_ERROR',
};
