export const LEGAL_INFORMATION_ACTION_TYPE = {
  LEGAL_INFORMATION_DATA_UPLOAD_PENDING:
    'LEGAL_INFORMATION_ACTION_TYPE.LEGAL_INFORMATION_DATA_UPLOAD_PENDING',
  LEGAL_INFORMATION_DATA_UPLOAD_SUCCESS:
    'LEGAL_INFORMATION_ACTION_TYPE.LEGAL_INFORMATION_DATA_UPLOAD_SUCCESS',
  LEGAL_INFORMATION_DATA_UPLOAD_ERROR:
    'LEGAL_INFORMATION_ACTION_TYPE.LEGAL_INFORMATION_DATA_UPLOAD_ERROR',
};
