export const MASTER_CLASS_PAGE_ACTION_TYPE = {
  MASTER_CLASS_DATA_UPLOAD_PENDING:
    'MASTER_CLASS_PAGE_ACTION_TYPE.MASTER_CLASS_DATA_UPLOAD_PENDING',
  MASTER_CLASS_DATA_UPLOAD_SUCCESS:
    'MASTER_CLASS_PAGE_ACTION_TYPE.MASTER_CLASS_DATA_UPLOAD_SUCCESS',
  MASTER_CLASS_DATA_UPLOAD_ERROR:
    'MASTER_CLASS_PAGE_ACTION_TYPE.MASTER_CLASS_DATA_UPLOAD_ERROR',
};
