export const MY_PURCHASES_ACTION_TYPE = {
  MY_PURCHASES_UPLOAD_PENDING: 'MY_PURCHASES_ACTION_TYPE.MY_PURCHASES_UPLOAD_PENDING',
  MY_PURCHASES_UPLOAD_SUCCESS: 'MY_PURCHASES_ACTION_TYPE.MY_PURCHASES_UPLOAD_SUCCESS',
  MY_PURCHASES_UPLOAD_ERROR: 'MY_PURCHASES_ACTION_TYPE.MY_PURCHASES_UPLOAD_ERROR',
};
