export const PRODUCT_ACTION_TYPE = {
  PRODUCT_UPLOAD_PENDING: 'PRODUCT_ACTION_TYPE.PRODUCT_UPLOAD_PENDING',
  PRODUCT_UPLOAD_SUCCESS: 'PRODUCT_ACTION_TYPE.PRODUCT_UPLOAD_SUCCESS',
  PRODUCT_UPLOAD_ERROR: 'PRODUCT_ACTION_TYPE.PRODUCT_UPLOAD_ERROR',
};
