export const SETTINGS_CHANGE_EMAIL_FIELD_NAME = {
  OLD_EMAIL: 'oldEmail',
  NEW_EMAIL: 'newEmail',
  EMAIL: 'email',
  PASSWORD: 'password',
};

export const SETTINGS_CHANGE_EMAIL_ACTION_TYPE = {
  SETTINGS_CHANGE_EMAIL_FORM_UPLOAD_PENDING:
    'SETTINGS_CHANGE_EMAIL_ACTION_TYPE.SETTINGS_CHANGE_EMAIL_FORM_UPLOAD_PENDING',
  SETTINGS_CHANGE_EMAIL_FORM_UPLOAD_SUCCESS:
    'SETTINGS_CHANGE_EMAIL_ACTION_TYPE.SETTINGS_CHANGE_EMAIL_FORM_UPLOAD_SUCCESS',
  SETTINGS_CHANGE_EMAIL_FORM_UPLOAD_ERROR:
    'SETTINGS_CHANGE_EMAIL_ACTION_TYPE.SETTINGS_CHANGE_EMAIL_FORM_UPLOAD_ERROR',
  SETTINGS_CHANGE_EMAIL_LOAD_EMAIL_PENDING:
    'SETTINGS_CHANGE_EMAIL_ACTION_TYPE.SETTINGS_CHANGE_EMAIL_LOAD_EMAIL_PENDING',
  SETTINGS_CHANGE_EMAIL_LOAD_EMAIL_SUCCESS:
    'SETTINGS_CHANGE_EMAIL_ACTION_TYPE.SETTINGS_CHANGE_EMAIL_LOAD_EMAIL_SUCCESS',
  SETTINGS_CHANGE_EMAIL_LOAD_EMAIL_ERROR:
    'SETTINGS_CHANGE_EMAIL_ACTION_TYPE.SETTINGS_CHANGE_EMAIL_LOAD_EMAIL_ERROR',
};
