import { SETTINGS_FORM_CHANGE_EMAIL_FIELD_KEY } from './frames/settings-form-change-email';

export const SETTINGS_CHANGE_EMAIL_FIELD_NAME = {
  OLD_EMAIL: 'oldEmail',
  NEW_EMAIL: 'newEmail',
  PASSWORD: 'password',
};

export const SETTINGS_CHANGE_PASSWORD_FORM_FIELD_NAME = {
  [SETTINGS_FORM_CHANGE_EMAIL_FIELD_KEY.OLD_EMAIL]:
    SETTINGS_CHANGE_EMAIL_FIELD_NAME.OLD_EMAIL,
  [SETTINGS_FORM_CHANGE_EMAIL_FIELD_KEY.NEW_EMAIL]:
    SETTINGS_CHANGE_EMAIL_FIELD_NAME.NEW_EMAIL,
  [SETTINGS_FORM_CHANGE_EMAIL_FIELD_KEY.PASSWORD]:
    SETTINGS_CHANGE_EMAIL_FIELD_NAME.PASSWORD,
};

export const SETTINGS_CHANGE_EMAIL_DATA_NAME = {
  EMAIL: 'email',
  PASSWORD: 'password',
};

export const SETTINGS_CHANGE_EMAIL_DATA_KEY = {
  EMAIL: 'EMAIL',
};

export const SETTINGS_CHANGE_EMAIL_ACTION_TYPE = {
  SETTINGS_CHANGE_EMAIL_FORM_UPLOAD_PENDING:
    'SETTINGS_CHANGE_EMAIL_ACTION_TYPE.SETTINGS_CHANGE_EMAIL_FORM_UPLOAD_PENDING',
  SETTINGS_CHANGE_EMAIL_FORM_UPLOAD_SUCCESS:
    'SETTINGS_CHANGE_EMAIL_ACTION_TYPE.SETTINGS_CHANGE_EMAIL_FORM_UPLOAD_SUCCESS',
  SETTINGS_CHANGE_EMAIL_FORM_UPLOAD_ERROR:
    'SETTINGS_CHANGE_EMAIL_ACTION_TYPE.SETTINGS_CHANGE_EMAIL_FORM_UPLOAD_ERROR',
  SETTINGS_CHANGE_EMAIL_LOAD_EMAIL_PENDING:
    'SETTINGS_CHANGE_EMAIL_ACTION_TYPE.SETTINGS_CHANGE_EMAIL_LOAD_EMAIL_PENDING',
  SETTINGS_CHANGE_EMAIL_LOAD_EMAIL_SUCCESS:
    'SETTINGS_CHANGE_EMAIL_ACTION_TYPE.SETTINGS_CHANGE_EMAIL_LOAD_EMAIL_SUCCESS',
  SETTINGS_CHANGE_EMAIL_LOAD_EMAIL_ERROR:
    'SETTINGS_CHANGE_EMAIL_ACTION_TYPE.SETTINGS_CHANGE_EMAIL_LOAD_EMAIL_ERROR',
};
