export const PATTERNS_PAGE_ACTION_TYPE = {
  PATTERNS_PAGE_UPLOAD_PENDING:
    'PATTERNS_PAGE_ACTION_TYPE.PATTERNS_PAGE_UPLOAD_PENDING',
  PATTERNS_PAGE_UPLOAD_SUCCESS:
    'PATTERNS_PAGE_ACTION_TYPE.PATTERNS_PAGE_UPLOAD_SUCCESS',
  PATTERNS_PAGE_UPLOAD_ERROR:
    'PATTERNS_PAGE_ACTION_TYPE.PATTERNS_PAGE_UPLOAD_ERROR',
};
