export const EDIT_COMPILATION_ACTION_TYPE = {
  EDIT_COMPILATION_UPLOAD_PENDING: 'EDIT_COMPILATION_ACTION_TYPE.EDIT_COMPILATION_UPLOAD_PENDING',
  EDIT_COMPILATION_UPLOAD_SUCCESS: 'EDIT_COMPILATION_ACTION_TYPE.EDIT_COMPILATION_UPLOAD_SUCCESS',
  EDIT_COMPILATION_UPLOAD_ERROR: 'EDIT_COMPILATION_ACTION_TYPE.EDIT_COMPILATION_UPLOAD_ERROR',
  PRODUCTS_UPLOAD_PENDING: 'PRODUCTS_ACTION_TYPE.PRODUCTS_UPLOAD_PENDING',
  PRODUCTS_UPLOAD_SUCCESS: 'PRODUCTS_ACTION_TYPE.PRODUCTS_UPLOAD_SUCCESS',
  PRODUCTS_UPLOAD_ERROR: 'PRODUCTS_ACTION_TYPE.PRODUCTS_UPLOAD_ERROR',
};
