export const EDIT_COMPILATION_ACTION_TYPE = {
  EDIT_COMPILATION_UPLOAD_PENDING: 'EDIT_COMPILATION_ACTION_TYPE.EDIT_COMPILATION_UPLOAD_PENDING',
  EDIT_COMPILATION_UPLOAD_SUCCESS: 'EDIT_COMPILATION_ACTION_TYPE.EDIT_COMPILATION_UPLOAD_SUCCESS',
  EDIT_COMPILATION_UPLOAD_ERROR: 'EDIT_COMPILATION_ACTION_TYPE.EDIT_COMPILATION_UPLOAD_ERROR',
};
