export const SEWING_GOODS_ACTION_TYPE = {
  RESET_PRODUCTS_STATE: 'SEWING_GOODS_ACTION_TYPE.RESET_PRODUCTS_STATE',
  SEWING_GOODS_UPLOAD_PENDING:
    'SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_UPLOAD_PENDING',
  SEWING_GOODS_UPLOAD_SUCCESS:
    'SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_UPLOAD_SUCCESS',
  SEWING_GOODS_UPLOAD_ERROR:
    'SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_UPLOAD_ERROR',
  SEWING_GOODS_UPDATE_PENDING:
    'SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_UPDATE_PENDING',
  SEWING_GOODS_UPDATE_SUCCESS:
    'SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_UPDATE_SUCCESS',
  SEWING_GOODS_UPDATE_ERROR:
    'SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_UPDATE_ERROR',
  CATEGORIES_UPLOAD_PENDING: 'SEWING_GOODS_ACTION_TYPE.CATEGORIES_UPLOAD_PENDING',
  CATEGORIES_UPLOAD_SUCCESS: 'SEWING_GOODS_ACTION_TYPE.CATEGORIES_UPLOAD_SUCCESS',
  CATEGORIES_UPLOAD_ERROR: 'SEWING_GOODS_ACTION_TYPE.CATEGORIES_UPLOAD_ERROR',
};
