export const SEWING_GOODS_ACTION_TYPE = {
  SEWING_GOODS_UPLOAD_PENDING:
    'SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_UPLOAD_PENDING',
  SEWING_GOODS_PAGINATION_SUCCESS:
    'SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_PAGINATION_SUCCESS',
  SEWING_GOODS_UPLOAD_SUCCESS:
    'SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_UPLOAD_SUCCESS',
  SEWING_GOODS_UPLOAD_ERROR:
    'SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_UPLOAD_ERROR',
  SEWING_GOODS_UPDATE_PENDING:
    'SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_UPDATE_PENDING',
  SEWING_GOODS_UPDATE_SUCCESS:
    'SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_UPDATE_SUCCESS',
  SEWING_GOODS_UPDATE_ERROR:
    'SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_UPDATE_ERROR',
};
