export const CREATE_ARTICLE_ACTION_TYPE = {
  CREATE_ARTICLE_UPLOAD_PENDING: 'CREATE_ARTICLE_ACTION_TYPE.CREATE_ARTICLE_UPLOAD_PENDING',
  CREATE_ARTICLE_UPLOAD_SUCCESS: 'CREATE_ARTICLE_ACTION_TYPE.CREATE_ARTICLE_UPLOAD_SUCCESS',
  CREATE_ARTICLE_UPLOAD_ERROR: 'CREATE_ARTICLE_ACTION_TYPE.CREATE_ARTICLE_UPLOAD_ERROR',
};
