import {
  SETTINGS_CHANGE_NOTIFICATION_DATA_NAME,
  SETTINGS_CHANGE_NOTIFICATION_FIELD_NAME,
  SETTINGS_CHANGE_NOTIFICATION_DATA_KEY,
} from './settings-change-notification.type';

export const convertSettingsChangeNotificationFormData = (data) => ({
  [SETTINGS_CHANGE_NOTIFICATION_DATA_NAME.SUBSCRIBE]:
    data[SETTINGS_CHANGE_NOTIFICATION_FIELD_NAME.NOTIFICATION],
});

export const performSettingsChangeNotificationLoadData = (data) => ({
  [SETTINGS_CHANGE_NOTIFICATION_DATA_KEY.SUBSCRIBED]:
    data[SETTINGS_CHANGE_NOTIFICATION_DATA_NAME.SUBSCRIBE],
});
