import { SETTINGS_FORM_CHANGE_NOTIFICATION_FIELD_KEY } from './frames/settings-form-change-notification';

export const SETTINGS_CHANGE_NOTIFICATION_FIELD_NAME = {
  NOTIFICATION: 'notification',
};

export const SETTINGS_CHANGE_NOTIFICATION_FORM_FIELD_NAME = {
  [SETTINGS_FORM_CHANGE_NOTIFICATION_FIELD_KEY.NOTIFICATION]:
    SETTINGS_CHANGE_NOTIFICATION_FIELD_NAME.NOTIFICATION,
};

export const SETTINGS_CHANGE_NOTIFICATION_DATA_NAME = {
  SUBSCRIBE: 'subscribe',
};

export const SETTINGS_CHANGE_NOTIFICATION_DATA_KEY = {
  SUBSCRIBED: 'SUBSCRIBED',
};

export const SETTINGS_CHANGE_NOTIFICATION_ACTION_TYPE = {
  SETTINGS_CHANGE_NOTIFICATION_FORM_UPLOAD_PENDING:
    'SETTINGS_CHANGE_NOTIFICATION_ACTION_TYPE.SETTINGS_CHANGE_NOTIFICATION_FORM_UPLOAD_PENDING',
  SETTINGS_CHANGE_NOTIFICATION_FORM_UPLOAD_SUCCESS:
    'SETTINGS_CHANGE_NOTIFICATION_ACTION_TYPE.SETTINGS_CHANGE_NOTIFICATION_FORM_UPLOAD_SUCCESS',
  SETTINGS_CHANGE_NOTIFICATION_FORM_UPLOAD_ERROR:
    'SETTINGS_CHANGE_NOTIFICATION_ACTION_TYPE.SETTINGS_CHANGE_NOTIFICATION_FORM_UPLOAD_ERROR',

  SETTINGS_CHANGE_NOTIFICATION_LOAD_NOTIFICATION_PENDING:
    'SETTINGS_CHANGE_NOTIFICATION_ACTION_TYPE.SETTINGS_CHANGE_NOTIFICATION_LOAD_NOTIFICATION_PENDING',
  SETTINGS_CHANGE_NOTIFICATION_LOAD_NOTIFICATION_SUCCESS:
    'SETTINGS_CHANGE_NOTIFICATION_ACTION_TYPE.SETTINGS_CHANGE_NOTIFICATION_LOAD_NOTIFICATION_SUCCESS',
  SETTINGS_CHANGE_NOTIFICATION_LOAD_NOTIFICATION_ERROR:
    'SETTINGS_CHANGE_NOTIFICATION_ACTION_TYPE.SETTINGS_CHANGE_NOTIFICATION_LOAD_NOTIFICATION_ERROR',
};
