export const FAQ_ARTICLE_ACTION_TYPE = {
  DATA_RELOAD: 'FAQ_ARTICLE_ACTION_TYPE.DATA_RELOAD',

  DATA_LOAD_PENDING: 'FAQ_ARTICLE_ACTION_TYPE.DATA_LOAD_PENDING',
  DATA_LOAD_SUCCESS: 'FAQ_ARTICLE_ACTION_TYPE.DATA_LOAD_SUCCESS',
  DATA_LOAD_ERROR: 'FAQ_ARTICLE_ACTION_TYPE.DATA_LOAD_ERROR',

  DATA_SAVE_PENDING: 'FAQ_ARTICLE_ACTION_TYPE.DATA_SAVE_PENDING',
  DATA_SAVE_SUCCESS: 'FAQ_ARTICLE_ACTION_TYPE.DATA_SAVE_SUCCESS',
  DATA_SAVE_ERROR: 'FAQ_ARTICLE_ACTION_TYPE.DATA_SAVE_ERROR',
};
