export const COMPILATION_ACTION_TYPE = {
  COMPILATION_UPLOAD_PENDING: 'COMPILATION_ACTION_TYPE.COMPILATION_UPLOAD_PENDING',
  COMPILATION_UPLOAD_SUCCESS: 'COMPILATION_ACTION_TYPE.COMPILATION_UPLOAD_SUCCESS',
  COMPILATION_UPLOAD_ERROR: 'COMPILATION_ACTION_TYPE.COMPILATION_UPLOAD_ERROR',
};
