export const COMMENT_ACTION_TYPE = {
  COMMENT_UPLOAD_PENDING: 'COMMENT_ACTION_TYPE.COMMENT_UPLOAD_PENDING',
  COMMENT_UPLOAD_SUCCESS: 'COMMENT_ACTION_TYPE.COMMENT_UPLOAD_SUCCESS',
  COMMENT_UPLOAD_ERROR: 'COMMENT_ACTION_TYPE.COMMENT_UPLOAD_ERROR',

  COMMENT_CREATE_PENDING: 'COMMENT_ACTION_TYPE.COMMENT_CREATE_PENDING',
  COMMENT_CREATE_SUCCESS: 'COMMENT_ACTION_TYPE.COMMENT_CREATE_SUCCESS',
  COMMENT_CREATE_ERROR: 'COMMENT_ACTION_TYPE.COMMENT_CREATE_ERROR',
};
