export const COMMENT_ACTION_TYPE = {
  COMMENT_UPLOAD_PENDING: 'COMMENT_ACTION_TYPE.COMMENT_UPLOAD_PENDING',
  COMMENT_UPLOAD_SUCCESS: 'COMMENT_ACTION_TYPE.COMMENT_UPLOAD_SUCCESS',
  COMMENT_UPLOAD_ERROR: 'COMMENT_ACTION_TYPE.COMMENT_UPLOAD_ERROR',

  COMMENT_CREATE_PENDING: 'COMMENT_ACTION_TYPE.COMMENT_CREATE_PENDING',
  COMMENT_CREATE_SUCCESS: 'COMMENT_ACTION_TYPE.COMMENT_CREATE_SUCCESS',
  COMMENT_CREATE_ERROR: 'COMMENT_ACTION_TYPE.COMMENT_CREATE_ERROR',

  SUB_COMMENT_CREATE_SUCCESS: 'COMMENT_ACTION_TYPE.SUB_COMMENT_CREATE_SUCCESS',

  COMMENT_UPDATE_PENDING: 'COMMENT_ACTION_TYPE.COMMENT_UPDATE_PENDING',
  COMMENT_UPDATE_SUCCESS: 'COMMENT_ACTION_TYPE.COMMENT_UPDATE_SUCCESS',
  COMMENT_UPDATE_ERROR: 'COMMENT_ACTION_TYPE.COMMENT_UPDATE_ERROR',

  SUB_COMMENT_UPDATE_PENDING: 'COMMENT_ACTION_TYPE.SUB_COMMENT_UPDATE_PENDING',
  SUB_COMMENT_UPDATE_SUCCESS: 'COMMENT_ACTION_TYPE.SUB_COMMENT_UPDATE_SUCCESS',
  SUB_COMMENT_UPDATE_ERROR: 'COMMENT_ACTION_TYPE.SUB_COMMENT_UPDATE_ERROR',
};
