export const CREATE_SEWING_GOODS__ACTION_TYPE = {
  CREATE_SEWING_GOODS_UPLOAD_PENDING:
    'CREATE_SEWING_GOODS_ACTION_TYPE.CREATE_SEWING_GOODS_UPLOAD_PENDING',
  CREATE_SEWING_GOODS_UPLOAD_SUCCESS:
    'CREATE_SEWING_GOODS_ACTION_TYPE.CREATE_SEWING_GOODS_UPLOAD_SUCCESS',
  CREATE_SEWING_GOODS_UPLOAD_ERROR:
    'CREATE_SEWING_GOODS_ACTION_TYPE.CREATE_SEWING_GOODS_UPLOAD_ERROR',
};

export const SEWING_GOODS_FIELD_NAME = {
  NAME: 'titleRu',
  DESCRIPTION: 'descriptionRu',
  MODIFIER: 'modifierRu',
  IMAGES: 'images',
  IMAGE: 'image',
  RECOMMENDATIONS: 'recommendation',
  CATEGORIES: 'categories',

  PRICE: 'price',
  DISCOUNT: 'discount',
  OPTION_TYPE: 'optionType',

  OPTIONS: 'options',
  OPTION_SIZE: 'size',
  OPTION_COLOR: 'colorRu',
  OPTION_PRICE: 'price',
  OPTION_DISCOUNT: 'discount',
};
