export const CREATE_SEWING_GOODS_ACTION_TYPE = {
  CREATE_SEWING_GOODS_UPLOAD_PENDING:
    'CREATE_SEWING_GOODS_ACTION_TYPE.CREATE_SEWING_GOODS_UPLOAD_PENDING',
  CREATE_SEWING_GOODS_UPLOAD_SUCCESS:
    'CREATE_SEWING_GOODS_ACTION_TYPE.CREATE_SEWING_GOODS_UPLOAD_SUCCESS',
  CREATE_SEWING_GOODS_UPLOAD_ERROR:
    'CREATE_SEWING_GOODS_ACTION_TYPE.CREATE_SEWING_GOODS_UPLOAD_ERROR',

  SEWING_GOODS_PRODUCT_LOAD_PENDING:
    'CREATE_SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_PRODUCT_LOAD_PENDING',
  SEWING_GOODS_PRODUCT_LOAD_SUCCESS:
    'CREATE_SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_PRODUCT_LOAD_SUCCESS',
  SEWING_GOODS_PRODUCT_LOAD_ERROR:
    'CREATE_SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_PRODUCT_LOAD_ERROR',

  SEWING_GOODS_PRODUCT_UPDATE_PENDING:
    'CREATE_SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_PRODUCT_UPDATE_PENDING',
  SEWING_GOODS_PRODUCT_UPDATE_SUCCESS:
    'CREATE_SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_PRODUCT_UPDATE_SUCCESS',
  SEWING_GOODS_PRODUCT_UPDATE_ERROR:
    'CREATE_SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_PRODUCT_UPDATE_ERROR',

  SEWING_GOODS_DELETE_PENDING:
    'CREATE_SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_DELETE_PENDING',
  SEWING_GOODS_DELETE_SUCCESS:
    'CREATE_SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_DELETE_SUCCESS',
  SEWING_GOODS_DELETE_ERROR:
    'CREATE_SEWING_GOODS_ACTION_TYPE.SEWING_GOODS_DELETE_ERROR',
};

export const SEWING_GOODS_FIELD_NAME = {
  NAME: 'titleRu',
  VENDOR_CODE: 'vendorCode',
  DESCRIPTION: 'descriptionRu',
  MODIFIER: 'modifierRu',
  IMAGES: 'images',
  IMAGE: 'image',
  RECOMMENDATIONS: 'recommendation',
  CATEGORIES: 'categories',

  PRICE: 'price',
  DISCOUNT: 'discount',
  COUNT: 'count',
  LENGTH: 'length',
  IS_COUNT: 'isCount',
  IS_LENGTH: 'isLength',
  OPTION_TYPE: 'optionType',

  OPTIONS: 'options',
  OPTION_SIZE: 'size',
  OPTION_COLOR: 'colorRu',
  OPTION_PRICE: 'price',
  OPTION_DISCOUNT: 'discount',
  OPTION_COUNT: 'count',
  OPTION_LENGTH: 'length',
  OPTION_VISIBILITY: 'optionVisibility',

  DELETED: 'deleted',
  IN_ENGLISH: 'inEnglish',
};
