export const CREATE_SEWING_GOODS__ACTION_TYPE = {
  CREATE_SEWING_GOODS_UPLOAD_PENDING:
    'CREATE_SEWING_GOODS_ACTION_TYPE.CREATE_SEWING_GOODS_UPLOAD_PENDING',
  CREATE_SEWING_GOODS_UPLOAD_SUCCESS:
    'CREATE_SEWING_GOODS_ACTION_TYPE.CREATE_SEWING_GOODS_UPLOAD_SUCCESS',
  CREATE_SEWING_GOODS_UPLOAD_ERROR:
    'CREATE_SEWING_GOODS_ACTION_TYPE.CREATE_SEWING_GOODS_UPLOAD_ERROR',
};

export const SEWING_GOODS_FIELD_NAME = {
  NAME: 'titleRu',
  DESCRIPTION: 'descriptionRu',
  TYPE: 'type',
  MODIFIER: 'modifier',
  DISCOUNT: 'discount',
  IMAGES: 'images',
  IMAGE: 'image',
  RECOMENDATIONS: 'recomendations',
  CATEGORIES: 'categories',
  CATEGORY: 'textRu',

  COUNT: 'count',

  SIZES: 'sizes',
  SIZE_NAME: 'size',
  SIZE_PRICE: 'price',

  COLORS: 'colors',
  COLOR_NAME: 'color',
  COLOR_PRICE: 'price',
};
