export const ARTICLES_ACTION_TYPE = {
  ARTICLES_UPLOAD_PENDING: 'ARTICLES_ACTION_TYPE.ARTICLES_UPLOAD_PENDING',
  ARTICLES_UPLOAD_SUCCESS: 'ARTICLES_ACTION_TYPE.ARTICLES_UPLOAD_SUCCESS',
  ARTICLES_PAGINATION_SUCCESS:
    'ARTICLES_ACTION_TYPE.ARTICLES_PAGINATION_SUCCESS',
  ARTICLES_UPLOAD_ERROR: 'ARTICLES_ACTION_TYPE.ARTICLES_UPLOAD_ERROR',
};
