import { ARTICLES_FORM_FILTER_FIELD_KEY } from './frames/articles-form-filter';

export const ARTICLES_FILTER_FIELD_NAME = {
  CATEGORY: 'category',
  TAGS: 'tags',
  FIND_ARTICLES: 'findArticles',
};

export const ARTICLES_FORM_FILTER_FIELD_NAME = {
  [ARTICLES_FORM_FILTER_FIELD_KEY.CATEGORY]:
    ARTICLES_FILTER_FIELD_NAME.CATEGORY,
  [ARTICLES_FORM_FILTER_FIELD_KEY.TAGS]: ARTICLES_FILTER_FIELD_NAME.TAGS,
  [ARTICLES_FORM_FILTER_FIELD_KEY.FIND_ARTICLES]:
    ARTICLES_FILTER_FIELD_NAME.FIND_ARTICLES,
};
