export const ARTICLES_FIELD_NAME = {
  CATEGORY: 'category',
  TAGS: 'tags',
  FIND_INPUT: 'find-articles',
};

export const ARTICLES_ACTION_TYPE = {
  ARTICLES_UPLOAD_PENDING: 'ARTICLES_ACTION_TYPE.ARTICLES_UPLOAD_PENDING',
  ARTICLES_UPLOAD_SUCCESS: 'ARTICLES_ACTION_TYPE.ARTICLES_UPLOAD_SUCCESS',
  ARTICLES_UPLOAD_ERROR: 'ARTICLES_ACTION_TYPE.ARTICLES_UPLOAD_ERROR',
};
